= Upgrading applications from XP7 to XP8
:toc: right
:imagesdir: images

This section describes the steps required to upgrade an XP application from 7.x to 8.0

NOTE: This section is only relevant when upgrading from XP7 to XP8.

== Preparations

Before you start the upgrade procedure:

* Make sure you have https://developer.enonic.com/docs/enonic-cli[Enonic CLI] installed
* Check out the project source code to a local folder i.e. myapp/

== Create a sandbox

To create the sandbox, go to your project folder and run the following command:

  enonic project sandbox

When the command has completed successfully, the sandbox will be associated with your project.
This enables us to build, deploy and test the application.

[TIP]
====
*Using Git?*
Enonic CLI adds a `.enonic` file to your project root, consider updating your `.gitignore` file with the following entry:

  ### Enonic ###
  .enonic
====

== Build system

The standard build system used for XP projects must be updated.

=== Gradle Wrapper

XP 8.0 standardizes on the use of Gradle 8.14.
We recommend bundling Gradle wrapper of version 8.14 or later in your project.

For simple installations, from your project root, run:

  ./gradle wrapper --gradle-version 8.14

This will install or update your project with a new Gradle wrapper.

Please, refer to Grade documentation for more details https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper

=== XP Gradle plugins

==== Application upgrade

If you are upgrading *an application*, you need to use version greater or equal to '3.6.1' of the XP Gradle plugin (_com.enonic.xp.app_).


This plugin expects application properties to be defined in the `app {}` section of _build.gradle_
and enables quick reference to the Enonic repo via _xp.enonicRepo()_ shortcut

NOTE: Syntax for adding plugins to Gradle may have changed for your project, we recommend the following updates to your build files:

.build.gradle sample
[source,groovy]
----
plugins {
    id 'com.enonic.xp.app' version '3.6.1'
}

app {
    name = "${appName}"
    displayName = "${appDisplayName}"
    vendorName = "${vendorName}"
    vendorUrl = "${vendorUrl}"
    systemVersion = "${xpVersion}"
}

dependencies {
    implementation "com.enonic.xp:script-api:${xpVersion}"
    include "com.enonic.xp:lib-content:${xpVersion}"
    include "com.enonic.xp:lib-portal:${xpVersion}"
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev') //TODO 'dev' is only while XP 8.0 is in development
}
----

Additionally, this is the recommended format for gradle.properties

.gradle.properties sample
[source,properties]
----
# Gradle Project settings
projectName = myproject
version = 1.0.0-SNAPSHOT

# XP App values
appDisplayName = My Cool App
appName = com.acme.something.myproject
vendorName = Acme Inc
vendorUrl = https://example.com
xpVersion = 8.0.0-SNAPSHOT #TODO 'dev' is only while XP 8.0 is in development

# Settings for publishing to a Maven repo
group = com.acme.something
----

NOTE: `appName` and `appDisplayName` are only used for application projects, as well as `app` config in `build.gradle`

==== Library upgrade

If you are upgrading *a library*, you don't need to use _com.enonic.xp.app_ plugin or have `app {}` section in _build.gradle_.
Below is a sample content of _build.gradle_ and _gradle.properties_ files for a library:

.build.gradle sample
[source,groovy]
----
plugins {
    id 'java'
    id 'maven-publish'
    id 'com.enonic.xp.base' version '3.6.1'
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev') //TODO 'dev' is only while XP 8.0 is in development
}


----

NOTE: You only need to use _com.enonic.xp.base_ plugin if you are using XP dependencies and need to shortlink to Enonic repo
via _xp.enonicRepo()_ shortcut


.gradle.properties sample
[source,properties]
----
group=com.mycompany.lib
projectName=mylib
xpVersion=8.0.0-SNAPSHOT #TODO 'dev' is only while XP 8.0 is in development
version=1.0.0-SNAPSHOT
----

=== Verify

After completing the steps above, you should now be able to test that your build is working, using the Enonic CLI:

  enonic project deploy

This command proxies the gradle wrapper, but also connects with the project sandbox.
You may also use `enonic project build` to build without deploying

NOTE: Projects containing Java code might get build errors at this point, otherwise the build should complete successfully.

== Default CMS repository

With XP 8, the default CMS repository `com.enonic.cms.default` is no longer created automatically. In fact, there is no default CMS repository at all. Existing `com.enonic.cms.default` repository is converted to a normal one without any special permissions or behavior.


== Widgets

Widgets are now an API
TODO


== Default context

In XP 8 context repository and branch may return null if they are not set. This is a default behavior. Previously the default context was set with `com.enonic.cms.default` repository and `draft` branch.

== JDK

Java 21 is required for XP 8.0.0

== Testing API

If you are using Enonic testing API (`com.enonic.xp:testing`)
You need to add Junit 5 dependency with the corresponding platform launcher.

[source,groovy]
----
dependencies {
testImplementation "com.enonic.xp:testing:${xpVersion}"
testImplementation(platform("org.junit:junit-bom:5.12.2"))
testImplementation 'org.junit.jupiter:junit-jupiter'
testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
----

Junit 4 is not supported in XP 8.0.0

== API Deprecations and Breaking Changes

=== HTTP Services

HTTP Services are deprecated. APIs should be used instead.

.Old services
[source,files]
----
src/
  main/
    resources/
      services/
        coolservice/
          coolservice.xml
          coolservice.js
      myservice/
        myservice.js
        myservice.xml
----

.New APIs
[source,files]
----
src/
  main/
    resources/
      apis/
        coolservice/
          coolservice.xml
          coolservice.js
        myservice/
          myservice.js
          myservice.xml
----

.Old service.xml
[source,xml]
----
<service>
  <allow>
    <principal>role:system.admin</principal>
  </allow>
</service>
----

.New api.xml
[source,xml]
----
<api>
  <allow>
    <principal>role:system.admin</principal>
  </allow>
</api>
----

In order for API to work on admin tool, site or webapp it must be mounted via the descriptor.

.Example of mounting "coolservice" API in an admin tool
[source,xml]
----
<tool xmlns="urn:enonic:xp:model:1.0">
  <display-name>My Admin Tool</display-name>
  <allow>
    <principal>role:system.admin</principal>
  </allow>
  <apis>
    <api>coolservice</api>
  </apis>
</tool>
----

=== Assets service

Assets service has been deprecated since XP 7.15
Use `lib-asset` instead.

TODO: Do we remove assets service?

=== lib-admin

`getAssetsUri` method is removed. Use `lib-asset` library instead.

`getBaseUri` method is removed. Use `getHomeToolUrl` instead.

`getLocale` method is removed without replacement.

`getLocales` method is removed. Use `request.locales` instead.

`getPhrases` method is removed. Use `lib-i18n` `getPhrases` instead.

`getLauncherUrl` and `getLauncherPath` methods are removed. Launcher is a widget now.

=== node-lib

`_inheritsPermissions` node property is removed. It can only be used as an argument in `create` method - to copy permissions from the parent node.

`setRootPermissions` method is removed. Use `applyPermissions` instead.

`modify` method is deprecated. Use `update` instead.

`editor` of deprecated `modify` method can no longer edit node permissions. Use separate call to `applyPermissions` method instead.

=== content-lib

`setPermissions` method is removed. Use `applyPermissions` instead.

`editor` of deprecated `modify` method can no longer edit content permissions. Use separate call to `applyPermissions` method instead.

`modify` method is deprecated. Use `update` instead.

`modifyMedia` method is deprecated. Use `updateMedia` instead.
