= Enonic XP NoSQL Data Repository
:toc: right
:imagesdir: images

Enonic XP ships with a unique and powerful document-oriented data repository which is built on top of the popular search engine "Elasticsearch".

== Features

The XP Repository enables you to store, index, query and access your data in many ways.
Below is a highlight of the capabilities provided:

* Create any number of repositories within a single deployment of XP
* Store and index documents - also known as <<Nodes>>
* Supports a vast range of <<value types>>, from strings to geolocation
* Use single value properties or arrays
* Efficiently supports storing <<Binary data>> such as files and byte arrays
* Query your data using the <<Enonic Query Language>>
* Powerful aggregations enable you to create visualizations or navigation
* Node-level versioning to support rollbacks
* Organize your data in tree structures
* <<Access Control>> down to a single document (also known as a node)
* Branches "Git style" enable you to stage your data
* Schema-less approach to keep domain model in your code
* Update your data with <<Editors>> (fragments on code that run on each document)
* <<Snapshot>> feature to rollback entire system or repositories

== Repositories

Repositories are the fundamental concept that enables you to create and store data in silos.
Each repository may be given a name, and can also be tuned for specific requirements.

== Nodes

Each entry in a repository is called a Node.
A node is essentially composed from a number of properties.

=== Properties
A property is essentially in the key-value, where the value has a specific value type, such as TextLine, or GeoPoint.
The value type is used to index the property correctly, and provide basic validation.

Additionally, a special value type known as "property set" enables creation of nested properties within a single node.

=== Value Types

== Enonic Query Language
