= Pagination
:toc: right
:imagesdir: images

When accessing the XP data storage, it is recommended to limit the number of items fetched in a single request.
To address this, all API methods support pagination.

== Start & count

When searching, the result will contain a number of matching nodes.
This number if given by the provided ``count`` parameter.
The result will also contain a value indicating the total number of hits for the search: ``total``.
The ``start`` parameter indicates from what position in the result set we should start retrieving results.

Lets consider a search matching 1000 documents.
Usually, one does not retrieve all these results at once,
but rather a subset of the result - and fetch the next subset of the result if necessary.
This type of data-retrieving is called paging.

Typically, one will decide the number of wanted results for each iteration, e.g 100:

* start = 0
* count = 100

Then, for the next iteration, we will start from the first result not retrieved in the first iteration:

* start = 100
* count = 100

The ``total`` return field can be used to create page-navigation for the search result, by dividing
the ``total`` hits by the page-size (``count``) to get the needed number of pages.


TODO: REAL EXAMPLES
