= HTTP controllers
:toc: right
:imagesdir: ../images

JavaScript controllers represent the core concept of the Enonic XP framework.

[#http-controller]
== Controller
HTTP controllers are essentially JavaScript files that are invoked by the various <<../runtime#,runtime engines>>, or by other controllers through the require system.

Common for all http controllers is that they export functions matching the desired HTTP Method it implements.
As such, any controller must explicitly declare one or more "exports" in order to handle requests:
`get`, `post`, `delete`, `patch` are examples of such methods.

NOTE: `patch` is supported starting from image:xp-7150.svg[XP 7.15.0,opts=inline].

A controller can also export a special function `all` which will handle any HTTP method, unless there is a more specific handler available.

The appropriate function will automatically be invoked for every request sent to the controller.

.Example usage
[source,javascript]
----
include::code/controller-1.js[]
----

A handler function receives a parameter with an <<http#http-request, Http Request>> object, and returns an <<http#http-response, HTTP Response>> object.

[source,javascript]
----
include::code/controller-2.js[]
----
