= HTTP
:toc: right
:imagesdir: framework/images

The XP framework lets developer build web based applications based on the following capabilities:

== HTTP Controllers

JavaScript http controllers simply export functions matching the desired HTTP Method it implements.
As such, any controller must explicitly declare one or more "exports" in order to handle requests:
``get``, ``post``, ``delete`` are examples of such methods.

A controller can also export a special function ``all`` which will handle any HTTP method, unless there is a more specific handler available.

The appropriate function will automatically be invoked for every request sent to the controller.

.Example usage
[source,javascript]
----
include::code/controller-1.js[]
----

A handler function receives a parameter with a ``request`` object, and returns a ``response`` object.

[source,javascript]
----
include::code/controller-2.js[]
----


== HTTP Request

The following object is passed along with every HTTP request. The object is similar to many traditional request objects, except for two special properties:
mode and branch. These properties are specific to the XP Portal, automatically indicating the contextual branch and rendering mode.

The ``request`` object represents the HTTP request and current context for the
controller.

[source,json]
----
{
  "method": "GET", <!--1-->
  "scheme": "http", <!--2-->
  "host": "enonic.com", <!--3-->
  "port": "80", <!--4-->
  "path": "/my/page", <!--5-->
  "url": "http://enonic.com/my/page?debug=true", <!--6-->
  "remoteAddress": "10.0.0.1", <!--7-->
  "mode": "edit", <!--8-->
  "branch": "master", <!--9-->
  "body": null <!--10-->
  "params": { <!--11-->
    "debug": "true"
  },
  "headers": { <!--12-->
    "Language": "en",
    "Cookies": "mycookie=123; other=abc;"
  },
  "cookies": { <!--13-->
    "mycookie": "123",
    "other": "abc"
  }
}
----

<1> HTTP method of the request
<2> Scheme used to make this request i.e. "http" / "https"
<3> Host name of the server to which the request was sent.
<4> Port of the server to which the request was sent.
<5> Path of the request
<6> URL of the request.
<7> IP address of the client that sent the request. If the X-Forwarded-For footnote:[http://en.wikipedia.org/wiki/X-Forwarded-For] header is set, its value will override the client IP.
<8> Rendering mode (used in site context) one of: ``inline``, ``edit``, ``preview``, ``live``.
<9> Contextual repository branch (used in site context), one of: ``draft``, ``master``.
<10> Optional string value
<11> Name/value pairs of the query/form parameters from the request.
<12> Name/value pairs of the HTTP request headers.
<13> Name/value pairs of the HTTP request cookies.

== HTTP Response

The ``response`` object is the value returned by an HTTP controller - as a response to an :ref:`http_request`.

[source,json]
----
{
  "status": 200, <!--1-->
  "body": "Hello World", <!--2-->
  "contentType": "text/plain", <!--3-->
  "headers": {  <!--4-->
      "key": "value"
  },
  "cookies": {},  <!--5-->
  "redirect": "/another/page",  <!--6-->
  "pageContributions": {},  <!--7-->
  "postProcess": true,  <!--8-->
  "applyFilters": true  <!--9-->
}
----

<1> HTTP response status code (default is ``200``).
<2> HTTP message body of the response that can either be a string or a JavaScript object.
<3> MIME type of the body (defaults to ``text/plain; charset=utf-8``).
<4> Name/value pairs with the HTTP headers to be added to the response.
<5> HTTP cookies to be added to the response. Will be described in a later section.
<6> URI to redirect to. If specified, the value will be set in the "Location" header and the status will be set to 303.
<7> A special filter available for sites and page components allowing page components to contribute html to the main page markup. See :ref:`page_contributions`
<8> Post-processing is a special filter for sites and pages, if enabled it will reprosess a page looking for page contributions and rendering components in a page. (See also :ref:`page_contributions`) (default is ``true``). Set to false if you want to speed up page rendering in cases where there are no regions or page components.
<9> Whether or not to execute the filters after rendering. Set to ``false`` to skip execution of filters. (See also :ref:`response_filters`) (default is ``true``).

== HTTP Cookies

There are two ways that Http Cookie values can be set in responses (see examples).

Here's an example of how the cookies are set:

[source,javascript]
----
return {
    status: 200,
    body: "Hello World",
    cookies: {
        "plain": "value", <!--1-->
        "complex": { <!--2-->
            value: "value", <!--3-->
            path: "/valid/path", <!--4-->
            domain: "enonic.com", <!--5-->
            comment: "Some cookie comments", <!--6-->
            maxAge: 2000, <!--7-->
            secure: false, <!--8-->
            httpOnly: false <!--9-->
        }
    }
};
----

<1> If the value is a string then the cookie is created using default settings.
<2> If the value is an object, it will try to apply the settings.
<3> Value (required) The value to store in the cookie. This example will create a cookie looking like this ``complex: value``.
<4> The paths on the site where this cookie should be available from (and all containing paths). Defaults to ``empty``
<5> Add additional sites that should be able to read the cookie. Defaults to ``empty`` (Only the server that creates the cookie can read it.)
<6> A comment describing the cookie. Default to ``null`.
<7> Number of **seconds** before the browser is allowed to delete the cookie. Defaults to ``-1`` (The cookie will live until the browser is shut down.)
<8> Control if the cookie should only be accepted to be created and read over https and similar secure protocols. Defaults to ``false``
<9> Control if the cookie is available for scripts or not. If `true`, only the serverside code can read the cookie. Defaults to ``false`` (Also client-side scripts can read the cookie.)

== Websockets

Websocket support allows a service to act as a websocket channel that
you can connect to from a web-browser.

A ``get`` method must be implemented to handle initialization
of the websocket.

[source,javascript]
----
include::code/websockets-1.js[]
----

A websocket event handler named ``webSocketEvent`` is required. It will be called for every websocket event from a client. See example below.

[source,javascript]
----
include::code/websockets-2.js[]
----

Below is an example of a simple chat. A library called ``lib-websocket`` has functions for sending messages back and adding/removing clients
in groups. Adding to groups allows for multicast message sending.

[source,javascript]
----
include::code/websockets-3.js[]
----

== Error handler

TODO: Work in progress

== HTTP Filters

TODO: Work in progress

JavaScript filters are only available for the site engine.
Webapp developers may simply use a https://market.enonic.com/vendors/enonic/router-lib[router] to achieve similar functionality.

Filters are essentially controllers added to the rendering pipeline before and/or after the normal request proccessing.

Like controllers, filters are triggered based on their exports.

For instance, expose two different methods,
