= Main controller
:toc: right
:imagesdir: framework/images

Handle application lifecycle events via the main controller.

== main.js
Enonic apps may contain a special controller known as the Application controller, or just "main.js".

Simply place the file `src/main/resources/main.js` into your project.

The `main.js` invoked when application starts. A common use of this controller is initialization like creating repositories, and registration of event listeners.

NOTE: `main.js` execution should complete as quickly as possible to prevent application stalling.

Never call remote endpoints or wait in loops for events inside `main.js` global scope.

TIP: If you need to perform time consuming work in the main controller, consider implementing it as a <<task#, task>>.

Simple example:

[source,javascript]
----
// Log application start
log.info('Application ' + app.name + ' started');
----

Running code on stop:

[source,javascript]
----
// Log application stop
__.disposer(function() {
    log.info('Application ' + app.name + ' stopped');
});

----
