= Response Processors
:toc: right
:imagesdir: images

A special filter, mainly used to inject page contributions.

NOTE: Response processors are only available in the <<../runtime/engines/site-engine#, Site Engine>>

== Introduction

Page processing occurs between the `component rendring` step, and the `contributions filter` in the <<../runtime/engines/site-engine#, site engine>> pipeline. 

Response processors are commonly used by apps that need to inject <<<<contributions#, page contributions>> without placing a component on the page.

Use case examples are:

* Dynamically adding page contributions (i.e. script tags)
* General manipulation of the response markup i.e. headers or body (i.e. adding SEO tags).

Consider using regular <<filters#, HTTP Filters>> for other use-cases.

NOTE: Page contributions will only be triggered if the response type is `text/html`

== Usage

To create a processor, place a controller file in you project folder `src/main/resources/site/processors` i.e. `src/main/resources/site/processors/myprocessor.js`

The controller must export a `responseProcessor`. Like other <<filters#, filters>>, responseProcessors receive both request and response objects.

Below is an example that dynamically adds a `bodyEnd` <<contributions#, page contribution>> to the response.

.processors/tracker.js
[source,js]
----
exports.responseProcessor = function (req, res) {
    var trackingScript = '<script src="http://some.cdn/js/tracker.js"></script>';

    // Check if contribution field exists, if not create it
    var bodyEnd = res.pageContributions.bodyEnd;
    if (!bodyEnd) {
        res.pageContributions.bodyEnd = [];
    }

    // Add contribution
    res.pageContributions.bodyEnd.push(trackingScript);

    return res;
};
----

== Triggering

To wire a processor into the execution pipeline, it must be declared in the app's <<../cms/sites#site_xml, site descriptor>>, and the application must be added to the respective site.

.site.xml
[source,xml]
<site>
  <processors>
    <response-processor name="tracker" order="10"/> // <1> <2>
  </processors>
  <form/>
</site>
----

<1> @name indicates name of the controller file
<2> @order indicates execution order, as described below

Response processors may change any of the values of the response object, that includes: HTTP status code, response body, HTTP headers, cookies and page contributions.
It is also possible to return the response object received without any changes.

== Execution order

An application may contain multiple processors.
Multiple applications can be added to a Site.
When a page is rendered, all processors are ordered and executed accordingly.

The order of execution is determined by the `order` value (as defined in the <<../cms/sites#site_xml, site descriptor>>) combined with the order of the application list within the site.

Processors with a *lower* order will be executed first (across all apps within the site).

In case there are several filters with the same ``order`` number, the position of the applications (as configured on the site) determines the order of execution.

NOTE: If `applyFilters` is set to `false` in the <<http#http-response, response object>>, the response processing will be stopped. Default value is `true`.
