= Aggregations
:toc: right
:imagesdir: ../images

== Introduction
With Aggregations, developers may extract statistical data from search results.
Aggregations can be used for anything from data visualization to creating navigational UI's.

Consider a query returning all nodes that have a property "price" less than, say, $100. Now, we want to divide the result nodes into ranges, say 0-$25, $25-$50 and so on. We also would like to know the average price for each category. This could be done by doing multiple separate queries and calculating the average manually, but this would be very inefficient and cumbersome. Luckily, aggregations solve these types of problems easily.

In some API functions it is possible to send in an aggregations expression object. This object is either in Java or a JSON like the following:

.Basic aggregation DSL
[source,json]
----
include::code/expr.json[]
----

There are two different types of aggregations:

Bucket aggregations:: A bucket aggregation places documents matching the query in a collection - a bucket. Each bucket has a key.
Metrics aggeregations:: A metric aggeregation computes metrics over a set of documents.

Typically, you will divide data into buckets and then use metric aggregations to calculate e.g average values,
sum, etc. for each bucket, if necessary.

== Aggregations

=== Term

The `terms` aggregation places documents into bucket based on property values. Each unique value of a property will
get its own bucket. Here's a list of properties:

field (string):: The property path.
size (int):: The number of bucket to return, ordered by the given orderType and orderDirection. Default to ``10``.
order (string):: How to order the results, type and direction. Default to ``_term ASC``.
image:xp-770.svg[XP 7.7.0,opts=inline] minDocCount (int):: Only include bucket in the result if number of hits is ``minDocCount`` or more. This parameter is optional.

Types:

  * `_term`: Alphabetic ordering of bucket keys.
  * `_count`: Numeric ordering of number of document in buckets.

.Sample term aggregation
[source,json]
----
include::code/terms-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/terms-result.json[]
----


=== Stats

The stats-aggregations calculates statistics over numeric values extracted from the aggregated documents. The following statistics are supported:

`avg`, `min`, `max`, `count`, and `sum`

Here's a list of properties:

field (string):: The property path.

.Sample stats aggregation
[source,json]
----
include::code/stats-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/stats-result.json[]
----

=== Min

image:xp-770.svg[XP 7.7.0,opts=inline] An aggregation that computes the minimum of the values in the current bucket. Here's the list of properties:

field (string):: The property path.

.Sample min aggregation
[source,json]
----
include::code/min-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/min-result.json[]
----

=== Max

image:xp-770.svg[XP 7.7.0,opts=inline] An aggregation that computes the maximum of the values in the current bucket. Here's the list of properties:

field (string):: The property path.

.Sample max aggregation
[source,json]
----
include::code/max-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/max-result.json[]
----

=== Value Count

image:xp-770.svg[XP 7.7.0,opts=inline] An aggregation that counts the number of values that current document set has for a specific field. Here's the list of properties:

field (string):: The property path.

.Sample value count aggregation
[source,json]
----
include::code/value-count-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/value-count-result.json[]
----

=== Range

The range aggregation query defines a set of ranges that represents a bucket.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Details
| field | string | The property path
| ranges | <<numeric_range,NumericRange>>[] | The range-buckets to create
|===

.Sample range aggregation
[source,json]
----
include::code/range-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/range-result.json[]
----


=== geoDistance

The geoDistance aggregation needs a defined range to split the documents into buckets.
Only documents with properties of type 'GeoPoint' will be considered in the ``geoDistance`` aggregation buckets.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Details
| field | string | The property path
| origin | <<origin,Origin>> | The GeoPoint from which the distance is measured.
| ranges | <<numeric_range,NumericRange>>[] | The range-buckets to create.
| unit | string | The measurement unit to use for the ranges. Legal values are either the full name or the abbreviation of the following: km (kilometers), m (meters), cm (centimeters), mm (millimeters), mi (miles), yd (yards), ft (feet), in (inch) or nmi (nauticalmiles or NM).
|===

.Sample geoDistance aggregation
[source,json]
----
include::code/geo-distance-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/geo-distance-result.json[]
----

[NOTE]
====
At the time of writing, there is only one way of find out which result belongs to which bucket:
By also sorting the result on geoDistance, and matching the order to the number of each bucket.
In a future version, there will easier ways of doing this.
====


=== dateRange

The dateRange aggregation query defines a set of date-ranges that represents a bucket. Only
documents with properties of type 'DateTime' will be considered in the ``dateRange`` aggregation buckets.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Details
| field | string | The property path
| format | string | The date-format of which the buckets will be formatted to on return. Defaults to ``yyyy-MM-dd'T'HH:mm:ss.SSSZ``.
| ranges | <<date_range,Date range>>[] | The range-buckets to create. Follows a special <<date_math_expression, Date-math expression>>.
|===


.Sample dateRange aggregation
[source,json]
----
include::code/date-range-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/date-range-result.json[]
----



==== Date-math expression
[#date_math_expression]

The range fields accepts a date-math expression to calculate the time-spans.

* Now minus a day: `now-1d`
* The given date minus 3 days plus one minute: `2014-12-10T10:00:00Z||-3h+1m`
* Range describing now plus one day and thirty minutes, rounded to minutes: `now+1d+30m/m`


=== dateHistogram

The date-histogram aggregation query defines a set of bucket based on a given time-unit. For instance,
if querying a set of log-events,  a ``dateHistorgram`` aggregations query with interval ``h`` (hour) will divide each log
event into a bucket for each hour in the time-span of the matching events. Here's a list of properties:

field (string):: The property path.
interval (string):: The time-unit interval for creating bucket. Supported time-unit notations:

  * ``y`` = Year
  * ``M`` = Month
  * ``w`` = Week
  * ``d`` = Day
  * ``h`` = Hour
  * ``m`` = Minute
  * ``s`` = Second

format (string):: Output format of date string.
minDocCount (int):: Only include bucket in result if number of hits <= ``minDocCount``.


.Sample dateHistogram aggregation
[source,json]
----
include::code/date-histogram-query.json[]
----

.Sample result from the above agg
[source,json]
----
include::code/date-histogram-result.json[]
----


== Types

=== Date range
[#date_range]

Defines a range to create a bucket for. `from` value will be included in the bucket, `to` will be excluded.
Values in `from` and `to` follow a special <<date_math_expression, Date-math expression>>.

[.lead]
Fields

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Details
| from | string | inclusive from
| to | string | exclusive to
|===


=== Numeric range
[#numeric_range]

Defines a range to create a bucket for. `from` value will be included in the bucket, `to` will be excluded.

[.lead]
Fields

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Details
| from | number | inclusive from
| to | number | exclusive to
|===

Examples:

[source,json]
----
{
  "to": 50 <1>
}
----
<1> The bucket will contain minus infinity unto 49.[overline]#999#

[source,json]
----
{
  "from": 50, <1>
  "to": 100 <2>
}
----
The bucket will contain

<1> 50
<2> unto 99.[overline]#999#

[source,json]
----
{
  "from": 100 <1>
}
----
<1> The bucket will contain 100 unto infinity

=== Origin
[#origin]

The GeoPoint from which the distance is measured.

[.lead]
Fields

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Details
| lat | number | Latitude
| lon | number | Longitude
|===

