= Highlighting
:toc: right
:imagesdir: images


== Introduction

Allows to highlight search results on one or more fields.The implementation uses the lucene highlighter.
The following is how search request body is look like:

.Query structure
[source,json]
----
{
    "query" : {...},
    "highlight" : {
        ... global properties ...

        "fields" : {
            "<fieldName>" : {
                ... field properties...
            }
        }
    }
}
----
In the above case, the content field will be highlighted for query (there will be another element in query result, called highlight
, which includes the highlighted fields and the highlighted fragments).

== Properties

encoder (string)::
Indicates if the snippet should be HTML encoded: `default` (no encoding) or `html`.

fragmenter (string)::
Specifies how text should be broken up in highlight snippets: `simple` or `span` (default).

fragmentSize (number)::
The size of the highlighted fragment in characters. Defaults to `100`.

numberOfFragments (number)::
The maximum number of fragments to return. If the number of fragments is set to 0, no fragments are returned.
If numberOfFragments is 0, fragmentSize is ignored.
Defaults to `5`.

noMatchSize (number)::
The amount of characters you want to return from the beginning of the field if there are no matching fragments to highlight. Defaults to `0` (nothing is returned).

order (string)::
Sorts highlighted fragments by score when set to `score`, will be displayed in the order fragments appear in the field by default (`none` value).

preTag (string)::
Use in conjunction with `postTag` to define the HTML tags to wrap the highlighted text. `<em>` by default.

postTag (string)::
Use in conjunction with `preTag` to define the HTML tags to wrap the highlighted text. `</em>` by default.

requireFieldMatch (boolean)::
Set to `false` if you want to highlight result in every listed field, regardless it was used in the query or not. Default is `true`.

tagsSchema (string)::
Set to `styled` to use the built-in tag schema.

Highlighting settings can be set on a global level and then overridden at the field level
(except `tagsSchema` and `encoder`, these two can be set only at the global layer).

== Highlighting Tags

By default, the highlighting will wrap highlighted text in `<em>` and `</em>`. This can be controlled by setting `prePag` and `postTag`, for example:

.Sample with custom tags

Request:
[source,json]
----
{
  "query": "fulltext('description', 'house garden')",
  "highlight": {
    "preTag": "<tag1>",
    "postTag": "</tag1>",
    "fields": {
      "description": {}
    }
  }
}
----

Response:
[source,json]
----
{
   ...
  "highlight": {
    "c4bb11f1-c6e2-4849-a665-28f612213984": {
      "description": [
        "Traditional <tag1>house</tag1> with big and well maintained <tag1>garden</tag1>."
      ]
    }
  }
}
----



== Encoder

An encoder parameter can be used to define how highlighted text will be encoded. `html` value will force escaping html, if you use html highlighting tags.

== Highlighted Fragments

Each field highlighted can control the size of the highlighted fragment in characters, and the maximum number of fragments to return.
On top of this it is possible to specify that highlighted fragments need to be sorted by score.
For example:

.Sample fragmentSize reducing

Request:
[source,json]
----
{
  query: "fulltext('description', 'house garden big')",
  highlight: {
    fields: {
      "description": {
        fragmentSize: 15,
        numberOfFragments: 2
      }
    }
  }
}
----

Response:
[source,json]
----
{
    ...
  "highlight": {
    "c4bb11f1-c6e2-4849-a665-28f612213984": {
      "description": [
        " <em>house</em> with <em>big</em>",
        " maintained <em>garden</em>."
      ]
    }
  }
}

----


If the number_of_fragments value is set to 0 then no fragments are produced, instead the whole content of the field is returned, and of course it is highlighted.

== Fragmenter

You can choose between the `simple`(used by default) and `span` fragmenters:

.Simple Fragmenter

Request:
[source,json]
----
{
  query: "fulltext('description', 'house garden')",
  highlight: {
    fragmentSize : 15,
    fragmenter: "simple",
    fields: {
      "description": {}
    }
  }
}
----

Response:
[source,json]
----
{
    ...
  "highlight": {
    "9922a270-f881-4bf8-be35-189e9a72a4f1": {
      "description": [
        "Traditional <em>house</em> with big and well maintained <em>garden</em>."
      ]
    }
  }
}

----

.Span Fragmenter

Request:
[source,json]
----
{
  query: "fulltext('description', 'house garden')",
  highlight: {
    fragmentSize : 15,
    fragmenter: "span",
    fields: {
      "description": {}
    }
  }
}
----

Response:
[source,json]
----
{
    ...
  "highlight": {
    "9922a270-f881-4bf8-be35-189e9a72a4f1": {
      "description": [
        " maintained <em>garden</em>.",
        " <em>house</em> with big"
      ]
    }
  }
}


----

== Tag Schema

There are also built in "tag" schemas, with currently a single schema called styled with the following tags:

[source,json]
----
<em class="hlt1">, <em class="hlt2">, <em class="hlt3">,
<em class="hlt4">, <em class="hlt5">, <em class="hlt6">,
<em class="hlt7">, <em class="hlt8">, <em class="hlt9">,
<em class="hlt10">
----

== Require Field Match

`requireFieldMatch` can be set to `false` which will cause any field to be highlighted regardless of whether the query matched specifically on them. The default behaviour is `true`, meaning that only fields that hold a query match will be highlighted.

.Sample with disabled `requireFieldMatch` property

Request:
[source,json]
----
{
  query: "fulltext('anyOtherField', 'house')",
  highlight: {
    requireFieldMatch: false,
    fields: {
      "description": {}
    }
  }
}
----

Response:
[source,json]
----
{
    ...
  "highlight": {
    "c4bb11f1-c6e2-4849-a665-28f612213984": {
      "description": [
        "Traditional <em>house</em> with big and well maintained garden."
      ]
    }
  }
}
----


== Global Settings

Highlighting settings can be set on a global level and then overridden at the field level.

.Sample global properties overridden for each field
[source,json]
----
{
    "query" : {...},
    "highlight" : {
        "numberOfFragments" : 3,
        "fragmentSize" : 150,
        "order": "none",
        "fields" : {
            "displayName" : { "numberOfFragments" : 0 },
            "description" : { "preTags" : ["<tag1>"], "postTags" : ["</tag1>"] },
            "data.address" : { "numberOfFragments" : 5, "order" : "score" }
        }
    }
}
----










