= NoSQL Data Store
:toc: right
:imagesdir: images

Enonic XP ships with a unique and powerful document-oriented data storage, built on top of the popular search engine "Elasticsearch".

== Background

Years of experience has taught us that traditional approaches to data storage (read SQL) are unsuited for modern cloud-based applications.
A key goal of Enonic XP was to deliver a complete stack - reducing the dependencies for complex infrastructure.

We evaluated many different technologies and found inspiration in everything from Git, File systems, Object storage, Java Content Repository, and Elasticsearch.
However, we were unable to find any single solution that was sufficiently simple and supported our requirements - so we decided to build our own technology.

The result is the Enonic Data Repository.

== Features

The XP Repository enables you to store, index, query and access data of virtually any kind. Fast and efficiently.
Below is a highlight of the capabilities provided:

* Create any number of <<repositories#>> within a single deployment of XP
* Store and index documents aka <<repositories#Nodes>>, no schemas required
* Nodes contain key-value entries called <<properties#>>
* A property may hold a single value, or an array of values
* Values have specific <<properties#Value Types>>, for instance String or GeoPoint
* Store entire files and byte arrays within a single property
* Build hierarchical structures of properties within a single node
* Nodes can be stored hierarchically
* Query your data using the <<Enonic Query Language>>
* Use <<Aggregations>> to get powerful statistics on your data
* Node-level <<Versioning>> lets you do rollbacks and store important events
* <<Access Control>> down to a single Node
* Git inspired <<Branches>> enable you to stage and promote your data
* Fully <<Schema-less>> approach lets you keep the domain model in your code
* <<Editors>> eliminate cumbersome statements
* <<Snapshot>> feature to rollback entire system or per repository
* <<Export and Import>> nodes in a human readable format
* <<Dump and Load>> your entire system to include all versions and data
