= Enonic Command Line Interface
:toc: right
:imagesdir: images

The Enonic Command Line Interface is central in building applications and performing common management tasks.


TODO: Installation of CLI


The CLI automates setting up new <<Projects>>, installation of <<Sandboxes>> development environment, as well as executing common management tasks.

== Project

By projects, we generally refer to code organized to build applications or libraries for XP.
Projects are commonly hosted in a Git repo, and needs to follow a set of principles to work with Enonic XP.

=== Project Create

To create a new project:

* Go to the directory where you wish to place your project
* Run `enonic project create`
* Complete the wizard
* Move into the newly create directory

todo

=== Project Build

To build your project, simply run `enonic project build`.

The build system helps you:

* Compiling code
* Run tests
* Create artifacts (executables)

The build system is based on https://gradle.org/[Gradle] and the https://plugins.gradle.org/plugin/com.enonic.xp.app[XP Gradle plugin].

The "project build" command is an alias for the Gradle Wrapper, which must be located in your project through a file called .gradlew (linux/mac) or gradlew.bat (windows).
The Gradle Wrapper is by default available with all https://market.enonic.com/starters[Starter Kits on Enonic Market].

NOTE: You may also the Gradle Wrapper directly by running `./gradlew build` (linux/mac) or `gradlew build` (windows) from your projects directory.


=== Project Deploy

Developers continuously need to deploy and test their code.

=== Libraries

To speed up development and enable a high degree of re-use,
applications can make use of Libraries in addition to your own custom code.

Libraries (and applications) are shared through so-called Maven repositories.
An example is https://repo.enonic.com. Anyone may configure and run their own repository - for internal as well as external use.


=== Deployment


== Sandboxes

Developers may use the CLI to run different instances of XP locally. These instances are called sandboxes.
Each sandbox will be associated with a specific distribution (version) of Enonic XP.

The CLI automates setting up, starting, stopping and upgrading sandboxes.




== Management tasks
