= Page components
:toc: right
:imagesdir: images

Pages are composed from a set of editorially manageable components.

== Regions
Regions are not strictly components themselves, but enable placement of components, kind of like a folder.
Regions have a fixed name, that is known to the component the region belongs to.

In Content Studio, regions are visually displayed as "dropzones" for components.

To exist, regions must actually be defined within another component. This definition is placed within the application code.
Only page and layout components support regions.

== Page

The page component is always the root entry of any component structure.
A page component may define zero, one, or multiple regions. Each region must have a unique name.

Conventionally, pages define a single region called "main".

To create a page component you must create the following files and folders in your project structure:

.page component project structure
[source,js]
----
/src/
  main/
    resources/
      site/
        pages/
          <component-name>/
            <component-name>.js
            <component-name>.xml
----
Replace <component-name> with your preferred name.

NOTE: The name you choose for a component will be used in the underlying data of the stored page. So choose your name wisely.

=== Page descriptor

The xml file placed in the component structure serves several purposes.

.Example page descriptor
[source,xml]
----
<page>
  <display-name i18n="component.page.name">My first page</display-name> <!--1--> <!--2-->
  <form/> <!--3-->
  <regions>
    <region name="main"/> <!--4-->
  </regions>
</page>
----

<1> *display-name* provides a display name used by the editorial interface
<2> *display-name/i18n* optionally specify localization key
<3> *form* allows the definition of a configuration form based on the <<schemas#,schema system>>
<4> *region* optionally specify regions for the page

=== Page controller

The page controller is essentially


=== Controller



== Layout

== Part

== Text

== Image

== Fragment
