= Sites
:toc: right
:imagesdir: images

== Introduction

A highly central component of the XP CMS are sites.
Site is shipped as a standard content type, which means it can easily be created and added by editors.
However, sites have an ability to let you add applications to them. Site applications isolated from <<projects#, projects>> applications. If a site needs an application from its project - add the application to the site.

Whenever an app is added to a site, all functionality and all content types from the app will be available within the scope of the site.

Only applications that declare support for sites can be added.
This is done via the descriptor file called site.xml

[#site_xml]
== site.xml

The site form serves multiple purposes:

* Declares that this app supports sites
* Lets you to configure the application on a per site basis
* Defines <<x-data#,X-data>> mappings for the site
* Defines bindings to Controllers as mappings and filters

The descriptor must be placed in your project as: `src/main/resources/site/site.xml`

.Minimal site.xml example
[source,xml]
----
<site>
  <form/>
</site>
----


.Site.xml with all options enabled
[source,xml]
----
<site>
  <processors> <!--1-->
    <response-processor name="tracker" order="10"/> <!--1--> <!--2-->
  </processors>
  <mappings> <!--2-->
     <mapping controller="/site/foobar/api.js" order="10">
       <pattern>/api/v\d+/.*</pattern>
     </mapping>
     <mapping controller="/site/pages/default/default.js">
       <match>type:'portal:fragment'</match>
     </mapping>
   </mappings>
   <x-data name="seo-settings"/> <!--3-->
   <form> <!--4-->
    <input type="TextLine" name="company">
      <label>Company</label>
      <occurrences minimum="1" maximum="1"/>
    </input>
    <mixin name="address"/>
  </form>
</site>
----

<1> Commonly used to add <<contributions#,page contributions>> to the response
<2> Controller and filter <<mappings#,mappings>> definitions
<3> Specify <<x-data#, X-data>> fields to add across content types within the site
<4> Define a <<./schemas#forms,form>> for this app. Used to add site specific configuration of the app
