= Custom styles
:toc: right
:imagesdir: images

XP supports implementation of custom styles that can be applied to page elements for more advanced rendering capabilities.

Styles are defined inside an application and can be applied to page elements using
https://developer.enonic.com/docs/content-studio/stable/editor/rich-text-editor#custom_image_styles[Rich Text Editor] in Content Studio.

NOTE: As of now custom styles are supported only for `<img>` elements.

== Declaration

=== Server-side processing

Define a file called `styles.xml` in the `site` folder of your app.

Each `image` field inside the root element declares a custom style for an `<img>` element, with corresponding `name` and style properties inside.

./site/styles.xml
[source,xml]
----
include::code/styles.xml[]
----

=== Client-side processing

Option attribute `css` on the root `styles` element allows mapping styles declares in this file with client-side CSS styles. In other words,
you can have styles with only server-side processing, or only client-side processing, or combine both under the same style name.

Define a file called `styles.css` inside `resources/assets` folder. It has to match the path in the `css` attribute of `styles` element
in `styles.xml`. So, in case of `css="styles/styles.css"` the file has to be located at `resources/assets/styles/styles.css`.


./site/styles.css
[source,css]
----
include::code/styles.css[]
----

NOTE: All custom styles (no matter if they define server-side processing or client-side processing or combine both) must be defined in `styles.xml`.

TIP: If you want to use client-side processing *only*, define a CSS file and add reference to it from `styles.xml` via `css` attribute (as described above).
Don't include any additional properties inside `<image>` elements but make sure that class name in the CSS file matches `image.name`
(like `editor-style-image-sepia` in `styles.xml` and `.editor-style-image-sepia` in `styles.css` from the example above).

== Image styles

By default, XP comes with one built-in image style called “_Original (no image processing)_”. By applying this style to the image, you'll make sure
that the image won't undergo any processing on the server and will be rendered “as is”.

The example above represents two styles - `editor-image-cinema` and `editor-style-image-sepia` - that apply server-side image processing.
One of them, `editor-style-image-sepia`, will also apply client-side styling to the image processed on the server.

NOTE: As of now, only `aspect-ratio` and `filter` are supported for server-side image processing.
