= Users and groups
:toc: right
:imagesdir: images

Users and groups exist in the scope of an ID provider.

== Users

Selected ID providers, such as the https://market.enonic.com/vendors/enonic/simple-idprovider[Simple ID provider^] let you create and manage users directly from the XP admin. Other ID providers allow for external control of users, such as the https://market.enonic.com/vendors/enonic/oidc-id-provider[OIDC ID provider^], where users are typically created and managed in the 3rd party system, and only appear in XP once they have signed in for the first time.

A user generally consist of the following fields:

* login (username)
* display name (Full name)
* e-mail

For a walkthrough of creating and editing users from the UI, see the <<../admin/users#users, Users admin tool>>.

=== Profiles

Developers may also store custom properties and values in the user object via `profiles`. This information is currently not visible or possible to edit via the Users App.

== Groups

Similar to users, groups are linked to an ID provider. Groups provide a flexible way to create and manage permissions, without assigning them on a per-user-basis

* You may add users to a group
* Roles may be granted to a group - Indirectly assigning the roles to the users of the group
* Groups may be added to a group - causing transitive resolution of permissions
