= Application development
:toc: right
:imagesdir: images

TODO

== Introduction


== CLI


== SDK


== Projects

To create an application you need to setup a project.
Projects contain all code and configuration required to build the application.

For more details, check out the <<../reference/projects/index#,project reference documentation>>.

== Languages

XP apps are powered by the <<../runtime/index#,XP runtime>>.

Applications are primarily created with JavaScript.
Serverside Javascript is made possible through our CommonJS based <<javascript#,Javascript Framework>>

XP applications can also make use of Java.

Developers with special requirements may take advantage of advanced platform capabilities such as exposing and consuming services from other applications within the same instance.
Learn more about <<java#,using Java in XP apps>>


== Build system

By default, XP projects use the https://gradle.org[Gradle build system], and with it the Maven package system.
A range of XP specific libraries are also available on <<Enonic Market>>, in addition to the <<../api/index#,standard libraries>>, included in the release of Enonic XP.
Front-end developers often make use of JavaScript specific build systems such as Webpack.


== Testing

TODO

== Continuous Deployment

TODO
