= Admin Engine
:toc: right
:imagesdir: images

TODO

The admin engine is a core part of the XP runtime.
It enables developers to extend the functionality of the XP Admin Console with custom admin apps.

== Introduction

Enonic XP provides a pluggable administrative interface, known as the <<../admin/index#, Admin Console>>.
The Admin console by default available on ``//<server>:<port>/admin/`` (i.e. "localhost:8080/admin/").

The admin engine handles all requests to admin apps.
Like the <<webapps#,Webapp Engine>> and <<sites#,Site Engine>>,
the admin engine is based directly on the <<../framework/index#, XP Framework>>.

== Admin tools

LOTS OF TODO
By default, XP ships with two standard admin tools, as described in the <<../admin/index#, Admin Console documentation>>

Each tools has its own icon in the launcher panel.
Admin tools are launched in their own separate browser tabs, running independently of any other admin components.

Compared to a basic webapp, the following

* A single XP application may contain multiple admin tools
* Access to an admin app typically requires authentication, and particular role memberships
* Admin tools are all served within the admin URL pattern. i.e.  ``//<server>:<port>/admin/tool/<tool-name>``
