= ID provider endpoint
:toc: right
:imagesdir: media

ID provider is implemented as a Universal API, and offers a contextual endpoint for communicating directly with any ID provider.

== Mount point

The IDprovider API is implicitly mounted across all web engines as `+/_/idprovider/<idprovider-name>+`. 

For a live deployment, it may be reached in a URL-pattern like this: `+company.com/_/idprovider/myidprovider+`

NOTE: The IDprovider instances available in a certain context is controlled by your vhost configuration.

== Request pipeline

The site pipeline is executed as a subset of the <<../engines#common_request_pipeline,common pipeline>>:

image::idprovider-pipeline.svg[ID provider rendering pipeline, 768px]

Login:: Fixed endpoint for logging in: `+/_/idprovider/<idprovider-name>/login+`.

Logout:: Fixed endpoint for logging out: `+/_/idprovider/<idprovider-name>/logout+`.

Controller:: All other request paths are routed to the ID providers, acting as a regular controller

== Implementation

For details on how to implement an ID provider, visit the <<../../framework/idprovider#, framework documentation>>
