= App engine
:toc: right
:imagesdir: images

We like to refer to Enonic XP as a "Cloud Operating System".
Like every OS, Enonic XP supports development and deployment of applications.

The XP Runtime is the foundation of every XP Application.

Once deployed, XP apps instantly get access to other platform services - such as the <<../nosql/index,NoSQL repository>> and <<../cms/index,Content Management System>>.
XP apps are not limited to being "Web apps”. They can also run background tasks, extend the Admin Console, power websites, offer web endpoints, and even expose internal API’s to other applications.

With XP you have the essential tools needed for delivering powerful cloud applications.

NOTE: If you are new to Enonic XP, we recommend visiting the https://developer.enonic.com/start[Getting Started documentation]

== Javascript
Most XP applications use the XP Javascript Framework.
The framework is based on the CommonJS specification, and is easy to use.

Learn more about the <<javascript#,Javascript Framework>>

== Java
XP runs on top of the Java Virtual Machine (JVM), and utilizes the powerful OSGi framework for isolating applications.
Developers with special requirements may utilize advanced platform capabilities such as exposing and consuming services from other applications within the same instance.

Learn more about <<java#,using Java in XP apps>>

== Assets

Web application and sites commonly require serving of assets such as javascript files, css and static images.
The XP App engine provides an out-of-the-box solution to this problem.

Learn more about <<assets#,serving Assets>>

== Application Life Cycle

XP applications may be installed, started, stopped and uninstalled.

Learn more about the <<life-cycle#,XP apps life cycle>>

== Web apps

A common use case for XP apps is to serve web applications, or simply deliver API endpoints.

Learn how to to build <<webapps#,XP Web apps>>


== Sites

XP includes a highly flexible and powerful CMS.
The CMS can be used in headless mode (raw data), it can be integrated directly in your webapp as a traditional site, or used in hybrid mode - doing both at the same time.

Learn more about the <<../cms/index#,Content Management System>>


== Services

Exposing endpoints and API's for web applications without dealing with hardcoded url mappings or occupying human readable paths is a common problem.
Enonic XP offers a standardized approach to providing an accessing endpoints that solve this issue.

Learn more about the services feature in Enonic XP: TODO LINK




TODO info about deploying XP apps.
