= Site engine
:toc: right
:imagesdir: images

Site engine is responsible for processing of site requests on the endpoint `:8080/site/<repo>/<branch>/*`

The site engine is directly based on XP's <<../framework#,JavaScript framework>>.
Sites are essentially content driven web apps.
In a traditional web app, the developers are controlling all URL patterns.
In a site however, the URLs are editorially controlled.
In XP this boils down to a mapping between content (page) and a controller.
XP sites also enable developers to take control over URL patterns when needed, through filters and mappings (as described below).

== Inline rendering pipeline

This section describes the standard pipeline involved in processing a page request i.e. ``:8080/site/<repo>/<branch>/<path-to-page>.

Request filters:: Request Javascript filters that must be defined in the site descriptor. Filters may choose to abort any further processing of the request.

Mappings:: Javascript controllers within a site based on path or content driven mapping in the site descriptor

Page rendering:: If the requested url patter matches a page (content with the same url pattern), the page controller is executed - if not, a 404 (or other error is thrown). Pages with regions will typically process all regions and leave component placeholders.

Components rendering:: If the page response type is HTML, any placeholders in the markup will be processed and rendered i.e. parts, and layouts. Components with layouts will leave new placeholders, and this step will be repeated until no placeholders remain.

Processors:: If the page response type is HTML, processors defined in the site descriptor will be executed. Processors typically manipulate the HTML by adding script tags from inlined components in the previous step.

Site response filters:: Available filters may also perform last minute tasks before the final response is delivered.


== Component rendering pipeline

Page components may also be directly accessed.
For instance, one may render only the first part within in a page's main region.

The url pattern for direct rendering is: `:8080/site/<repo>/<branch>/<path-to-page>/_/component/<region>/#`. i.e. :8080/site/default/master/mysite/_/component/main/0`.

Component rendering::  In this mode, only the *component rendering* step (as described above) will be executed.

[NOTE]
====
By implementing `exports.post()` or any other HTTP methods in the component controller, it may also be used to act as the backend for your component.

Developers may also check if a component is rendered inline, or directly by using the request context.
This may for instance be used to produce JSON in direct rendering mode rather than HTML, which is mandatory for inline mode.
====
