= Admin Engine
:toc: right
:imagesdir: images

The admin engine is a core part of the XP runtime.
It enables developers to extend the functionality of the XP Admin Console with custom admin apps.

== Introduction

Enonic XP provides a pluggable administrative interface, known as the <<../admin#admin_console,Admin Console>>.
The Admin console by default available on ``//<server>:<port>/admin/`` (i.e. "localhost:8080/admin/").

The admin engine handles all requests to admin apps.
Like the <<../runtime#webapp-engine,Webapp Engine>> and <<../runtime#site-engine,Site Engine>>,
the admin engine is based directly on the <<../framework#, XP Framework>>.

== Admin tools

By default, XP ships with two standard admin tools, as described in the <<../admin#, Admin Console documentation>>

Each tool has its own icon in the launcher panel.
Admin tools are launched in their own separate browser tabs, running independently of any other admin components.

Compared to a basic webapp, the following

* A single XP application may contain multiple admin tools
* Access to an admin tool typically requires authentication, and particular role memberships
* Admin tools are all served within the admin URL pattern. i.e.  ``//<server>:<port>/admin/tool/<tool-name>``
