= Contributing to Translations
:toc: right
:imagesdir: images

We would greatly appreciate help with translating our Admin Console to more languages.  Here is a guide on how to contribute:

First, you need to fork the repository on GitHub, then checkout your fork to your local machine. After that, create language files for the specific language you can provide a translation for.
When the translation is complete, a pull request should be sent to Enonic, so we can include the file in the next distribution.

== Translating files

To provide a translation, please start with the English original phrase files and make a copy of each of them in the same folder, extending the main filename with ``_<language-code>``.
If, for instance, you want to make a translation to Spanish, the copied files should be called ``common_es.properties`` or ``phrases_es.properties``.
In the copied files, you may now translate all the English text into your preferred language.
When done, please submit a pull request from your fork to the upstream project with the translations.

== File locations

XP is split into multiple projects: one basic runtime, some libraries, and several apps. All code is found on GitHub:

[IMPORTANT]
--
Before making changes, fork the repositories listed below to your own GitHub account.
After forking, clone your fork to your local machine using:

 git clone git@github.com:<your-username>/<repository-name>.git
--

=== Admin Home App

[cols="2,5a"]
|===
| *GitHub URL* | https://github.com/enonic/app-admin-home
| *Checkout command* | ``git clone git@github.com:<your-username>/app-admin-home.git``
| *Original file in English* | ``/src/main/resources/i18n/phrases.properties``
|===

=== Admin UI Library

[cols="2,5a"]
|===
| *GitHub URL* | https://github.com/enonic/lib-admin-ui
| *Checkout command* | ``git clone git@github.com:<your-username>/lib-admin-ui.git``
| *Original file in English* | ``/src/main/resources/admin/i18n/common.properties``
|===

=== Applications App

[cols="2,5a"]
|===
| *GitHub URL* | https://github.com/enonic/app-applications
| *Checkout command* | ``git clone git@github.com:<your-username>/app-applications.git``
| *Original file in English* | ``/src/main/resources/i18n/phrases.properties``
|===

=== Content Studio

[cols="2,5a"]
|===
| *GitHub URL* | https://github.com/enonic/app-contentstudio
| *Checkout command* | ``git clone git@github.com:<your-username>/app-contentstudio.git``
| *Original files in English* |
``/modules/lib/src/main/resources/i18n/cs-plus.properties``
``/modules/lib/src/main/resources/i18n/dialogs.properties``
``/modules/lib/src/main/resources/i18n/page-editor.properties``
``/modules/lib/src/main/resources/i18n/phrases.properties``
``/modules/lib/src/main/resources/i18n/wcag.properties``
|===

=== Standard ID Provider

[cols="2,5a"]
|===
| *GitHub URL* | https://github.com/enonic/app-standardidprovider
| *Checkout command* | ``git clone git@github.com:<your-username>/app-standardidprovider.git``
| *Original file in English* | ``/src/main/resources/i18n/phrases.properties``
|===

=== Users App

[cols="2,5a"]
|===
| *GitHub URL* | https://github.com/enonic/app-users
| *Checkout command* | ``git clone git@github.com:<your-username>/app-users.git``
| *Original file in English* | ``/src/main/resources/i18n/phrases.properties``
|===

=== XP Runtime

[cols="2,5a"]
|===
| *GitHub URL* | https://github.com/enonic/xp
| *Checkout command* | ``git clone git@github.com:<your-username>/xp.git``
| *Original file in English* | ``/modules/app/app-system/src/main/resources/i18n/phrases.properties``
|===
