= NoSQL Data Store
:toc: right
:imagesdir: images

Enonic XP ships with a unique and powerful document-oriented data storage, built on top of the popular search engine Elasticsearch[https://elastic.com].

== Background

Years of experience has taught us that transactional storage models (read SQL) rarely fulfill the requirements of modern cloud-based applications.
A key goal of Enonic XP was to deliver a complete stack - reducing the dependencies for complex infrastructure.

We evaluated many different technologies and found inspiration in everything from Git, File systems, Object storage, Java Content Repository, and Elasticsearch.
However, we were unable to find any single solution that was sufficiently simple and supported our requirements - so we decided to build our own technology.

The result is the Enonic Data Repository.

== Features

The XP Repository enables you to store, index, query and access data of virtually any kind. Fast and efficiently.
Below is a highlight of the capabilities provided:

* Create any number of <<repositories#>> within a single deployment of XP
* Store and index documents aka <<nodes#>>, no schemas required
* Nodes contain key-value entries called <<nodes#Properties>>
* Nodes can be stored hierarchically
* Values have specific <<nodes#Value Types>>, for instance String or GeoPoint
* Store entire files and byte arrays within a single property
* Build hierarchical structures of properties within a single node
* Query your data using the <<eql#>>
* Use <<eql#Aggregations>> to get powerful statistics on your data
* Node-level <<Versioning>> lets you do rollbacks and store important events
* <<Access Control>> down to a single Node
* Git inspired <<Branches>> enable you to stage and promote your data
* Fully <<Schema-less>> approach lets you keep the domain model in your code
* <<Editors>> eliminate cumbersome statements
* <<Snapshot>> feature to rollback entire system or per repository
* <<Export and Import>> nodes in a human readable format
* <<Dump and Load>> your entire system to include all versions and data
