= XP Applications
:toc: right
:imagesdir: images

Similar to an Operating System, Enonic XP supports development and deployment of applications.

== Introduction

== Enonic Market

TODO


== Installation

There are essentially two ways you can install applications on Enonic XP:

* Via API
* Via file system

File system deployment is most commonly used in development phases,
but it can also be applied for specialized deployments scenarios.

Applications installed through the API will be available for all nodes in the XP cluster.

== Life Cycle

Once installed, XP applications may be started, stopped and uninstalled.
This is referred to as the life cycle of the application.
During the various steps, the applications themself may execute code.

Starting:: Once installed, applications are automatically started on all nodes.
During the startup, if it exists, the application's main.js script will be executed.
At a lower level, Java developers may utilize so-called OSGi lifecycle events for similar purposes.

Stopping:: Before an application is stopped, a special event is thrown.
Applications may also react to these events before they are shut down.

== Configuration

Applications can be configured with deployment specific setting per node in the cluster.
The configuration will automatically be injected when the applications starts.

Configuration files may be updated, and trigger a restart of the application, without restarting the XP nodes.
This means that for instance sessions, or open websocket connections will not be recycled, even if an application is restarted.

TODO: Link to info about configuration management


== Development

To create an application you need to setup a project.
Projects contain all code and configuration required to build the application.

For more details, check out the <<../reference/projects/index#,project reference documentation>>.

=== Languages

XP apps are powered by the <<../runtime/index#,XP runtime>>.

Applications are primarily created with JavaScript.
Serverside Javascript is made possible through our CommonJS based <<javascript#,Javascript Framework>>

XP applications can also make use of Java.

Developers with special requirements may take advantage of advanced platform capabilities such as exposing and consuming services from other applications within the same instance.
Learn more about <<java#,using Java in XP apps>>


=== Build system

By default, XP projects use the https://gradle.org[Gradle build system], and with it the Maven package system.
A range of XP specific libraries are also available on <<Enonic Market>>, in addition to the <<../api/index#,standard libraries>>, included in the release of Enonic XP.
Front-end developers often make use of JavaScript specific build systems such as Webpack.




== Use cases

=== Web apps

The JavaScript framework offers an easy way to build and is to serve web applications.
An XP app may only contain a single web app.

Web apps are created by adding a <<../reference/controllers/index#,controller file>> to your project.

Read more about <<../reference/web-engine/index#,web apps and the web engine>>

=== Sites

A unique feature of XP is the embedded Content Management capabilities.

You may build applications that go from serving content from an API (Headless CMS)
via traditional web sites to Hybrid CMS - offering the best of both worlds.

The CMS offering essentially consist of three parts:

* Content Studio - Editorial admin interface, available as an app on Enonic Market
* Content API - Built on top of the NoSQL Storage
* Site Engine - Built on top of the webapp engine

Learn more about the <<../cms/index#,Content Management System>>

=== ID providers

XP apps may also act as a so-called ID provider.
Once installed and configured, an ID provider can join the request pipeline of other sites and applications,
dynamically providing authentication and authorization when needed.
There are multiple standard ID providers available on Enonic Market.

Learn more about the <<../idprovider/index#,ID providers>>

=== Tasks

The XP runtime also supports executing scripts running in the background.
Unlike sites and web-applications, tasks are not exposed as an end-point.
Tasks can be started and monitored via the the task API
Tasks are made by adding one or more JavaScript controllers to your project.

Read more about <<../reference/tasks#,Tasks>>

=== Admin apps

XP apps can also contribute to Enonic XP's admin console.
The platform comes with a standardized approach to extend the admin console with custom interfaces, called admin apps.
Admin apps are created by adding one or more JavaScript controllers to your project.

Read more about <<../reference/admin-apps#,Admin apps>>


== Assets

Web application and sites commonly require serving of assets such as javascript files, css and static images.
The XP App engine provides an out-of-the-box solution to this known as the <<../reference/assets#,Asset service>>

== Services

When building web apps, web sites or even extending the XP admin,
exposing and consuming contextual endpoints without dealing with hardcoded url mappings is useful.
Enonic XP offers a practical approach to this called HTTP Services.
Services are made by adding one or more JavaScript controllers to your project.

Learn more about <<../reference/services#,Http Services>>


== Localization

TODO
