= Virtual Applications
:toc: right
:imagesdir: ../images

image:xp-7110.svg[XP 7.11.0,opts=inline]

Virtual Applications allow to extend/override schemas and descriptors from usual bundled application or create a standalone application container. Applications, schemas and descriptors data are stored in nodes in separate `system.app` repository. Use <<../api/lib-app, lib-app>> to manipulate virtual applications.


=== Structure
Virtual application node structure follows bundled applications site's file structure:
[source,files]
----
virtual-app/
    site/
      content-types/
      layouts/
      mixins/
      pages/
      parts/
      x-data/
      site.xml
      styles.xml

----
Use <<../api/lib-schema, lib-schema>> to manipulate schemas and descriptors of virtual apps.

=== Application Mode
Depending on app data and config, the application can work with its resources in different ways:

VIRTUAL::
Shows that only virtual application is presented in the system and support of virtual apps is enabled.
BUNDLED::
Shows one of the next cases:
- Only bundled application is presented in the system.
- Both bundled and virtual applications are presented, but bundled resources override virtual.
- Both bundled and virtual applications are presented, but virtual app support is disabled.
AUGMENTED::
Both bundled and virtual applications are presented in the system and virtual resources override bundled.

Check the <<../deployment/config#application, documentation>> to find out how to configure application behaviour.
