= Universal API WIP

Universal API enables mounting of <<../../framework/http#http-controller,http controllers>> safely made available on `/api` enpdoint as well as within an application (or site's) URL space, without the use of routers. It supports Headless approach or <<site-engine#,Site engine>>, <<webapp-engine#,Webapp engine>> and <<admin-engine#,Admin engine>> needs to access dynamic data, like REST API, GraphQL API, or other data sources.

API Engine is made with security in mind:

- It is not mounted anywhere by default, so you don't need to worry about accidental exposure of an admin API on a site.
- Mounting of API is granular and must be explicitly specified in engine descriptor files. If API is desined for a webapp, it will not be automatically mounted on a site.
- There is a singular mounting location of an API - to avoid cache pollution and allow strict control of URL patterns in WAF.
- It requires to specify principals granted access to an API. Developers need to think about API access rights in advance.

== Controller

To create an API, place an http controller file in the `src/main/resources/apis/` structure of your project.
Each controller needs to be placed in a folder matching its name i.e.: `src/main/resources/api/myapi/myapi.js`

Example service controller

.src/main/resources/apis/<api-name>/<api-name>.js
[source,JavaScript]
----
exports.get = function(req) {
  return {
    body: {
      time: new Date()
    },
    contentType: 'application/json; charset=utf-8'
  };
};
----

[#descriptor]
== Descriptor

API descriptor is required. It provides a way to define the API's roles, availability on `/api` endpoint as well as display name, description and documentation URL.

Example of Full API descriptor:
[source,xml]
----
<api>
  <mount>true</mount> <--1-->
  <display-name>My API</display-name> <--2-->
  <description>API for My App</description> <--3-->
  <documentation-url>https://developer.enonic.com/docs/api</documentation-url> <--4-->
  <allow> <--5-->
    <principal>role:system.admin</principal>
    <principal>role:myapp.myrole</principal>
  </allow>
</api>
----

<1> By default, APIs are not mounted on the <<#endpoint,Generic API endpoint>>.
To enable it, `<mount>true</mount>` should be set in the descriptor.
+
<2> *display-name* is the name of the API that will be shown in the UI.

<3> *description* is a short description of the API that will be shown in the UI.

<4> *documentation-url* is a link to the API documentation that will be shown in the UI.

<5> APIs must list principles that have access to it. It is required to specify at least one principal. Use `role:system.everyone` to make API public.

[#endpoint]
== Endpoint

API mount is context-aware:

- Generic API endpoint `+/api/<app-name>/<api-name>/+`
- For `site` engine: `+/site/<site-path>/_/<app-name>/<api-name>/+`
- For `webapp` engine: `+(/webapp/<app-name>/_/<app-name>/<api-name>/+`
- For `admin` engine: `+/admin/_/<app-name>/<api-name>/+`

Engine descriptors need to specify the available API names in the `api` element, while Generic API endpoint can be disabled in <<#descriptor,API Descriptor>> itself.

Example site descriptor with mounting of self-contained and external APIs:
[source,xml]
----
<site xmlns="urn:enonic:xp:model:1.0">
  <apis>
        <api>ws</api>
        <api>api-app:graphql</api>
  </apis>
  <form/>
</site>
----

== apiUrl()

To safely generate an API URL, use the `apiUrl()` function that is part of the <<../../api/lib-portal#,Portal Library>>.

NOTE: When invoked, the function will generate a contextual service url based on the context of the current controller.
