= Context Library
include::../variables.adoc[]
:toc: right
:imagesdir: images

This library contains functions to access and use the current context.  It comes bundled with the XP runtime, so it should always use the same version as XP.

== Usage

Add the following into your `build.gradle` file:

[source,groovy]
----
dependencies {
  include 'com.enonic.xp:lib-context:${xpVersion}
}
----

In your JavaScript controller, add a require statement:

[source,js]
----
const contextLib = require('/lib/xp/context');
----

You are now free to invoke to use the library functionality.


== Functions

=== get

Returns the current context

*Parameters*

None

*Returns*

<<Context>>

*Example*

.Getting the current context
[source,js]
----
const result = contextLib.get();
----

.Sample response
[source,js]
----
{
  branch: 'draft',
  repository: 'com.enonic.cms.default',
  authInfo: {
      principals: [
          'user:system:anonymous',
          'role:system.everyone'
      ]
  }
}
----



=== run

Runs a function within a custom context.
Commonly used when accessing repositories, or to override current users permissions.

*Parameters*

[cols="1%s,99%a"]
[frame="none"]
[grid="none"]
|============================
|*context*| Define a custom context to be used for the scope of the callback function
|*callback*|  Function to execute
|============================


*Returns*

The function execution will return a string with the result of the execution.


*Example*

.Run a simple function in a different context
[source,js]
----
// Define the callback to be executed.
function callback() {
    return 'Hello from context';
}

// Executes function within a custom context.
const result = contextLib.run({
    repository: 'system-repo',
    branch: 'master',
    user: {
        login: 'su', <1>
        idProvider: 'system'
    },
    principals: ["role:system.admin"],
    attributes: {
        ignorePublishTimes: true
    }
}, callback);
----

== Objects

=== Context

The context object is always available within the scope of a request

.Sample context object
[source,js]
----
{
  repository: 'some.repo.name', <1>
  branch: 'master', <2>
  user: { <3>
      login: 'mylogin',
      idProvider: 'idprovidername'
  },
  principals: ['role:system.admin'], <4>
  attributes: { <5>
      optionalAttributes: 'of any kind'
      }
}
----

<1> *repository* (_string_) Repository context.
<2> *branch* (_string_) Branch context.
<3> *user* (_object_) Specify a valid user/idprovider combination
<4> *principals* (_object_) Roles or group principals applicable for current user
<5> *attributes* (_object_) custom attributes
