= Grid Library

:toc: right
:imagesdir: ../images

image:xp-710.svg[XP 7.10.0,opts=inline] This library contains functions to share data across all applications and cluster nodes.

NOTE: Due to distributed nature of the `SharedMap` not all value types can be used. Strings, numbers, and pure JSON objects are supported. There is no runtime check for type compatibility due to performance reasons. The developer is also responsible for NOT modifying shared objects (keys and values) in place.

== Usage

Add the following dependency to your `build.gradle` file:

[source,groovy]
----
dependencies {
  include "com.enonic.xp:lib-grid:${xpVersion}"
}
----

In your JavaScript controller, add a `require` statement:

[source,js]
----
const gridLib = require('/lib/xp/grid');
----

You are now free to use the library functionality.

== Functions

=== getMap

This function returns an instance of `SharedMap` by the specified map identifier.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind   | Description
| key  | string | map identifier
|===

[.lead]
Returns

*SharedMap* :
JS object.

[source,js]
----
const gridLib = require('/lib/xp/grid');

var sharedMap = gridLib.getMap('mapId');
----

== Below are available functions for the `SharedMap` type.

=== set

Puts an entry into this map with a given time to live (TTL).

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name  | Kind   | Description
| key   | string | key of the entry
| value | string\|number\|boolean\|JSON\|null | value of the entry
| ttlSeconds  | number | maximum time to live in seconds for this entry to stay in the map. (0 means infinite, negative means map config default or infinite if map config is not available)
|===

[source,js]
----
const gridLib = require('/lib/xp/grid');

const sharedMap = gridLib.getMap('mapId');

sharedMap.set({
  key: 'key',
  value: 'value',
  ttlSeconds: 2 * 60 * 1000
});
----


=== get

Returns the value to which the specified key is mapped, or null if this map contains no mapping for the key.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind   | Description
| key  | string | key the key whose associated value is to be returned
|===

[source,js]
----
const gridLib = require('/lib/xp/grid');

const sharedMap = gridLib.getMap('mapId');

let value = sharedMap.get('key');
----

=== delete

Removes the mapping for the key from this map if it is present.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind   | Description
| key  | string | the key whose associated value is to be removed
|===

[source,js]
----
const gridLib = require('/lib/xp/grid');

const sharedMap = gridLib.getMap('mapId');

sharedMap.delete('key');
----

=== modify

Attempts to compute a mapping for the specified key and its current mapped value.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name       | Kind      | Description
| key        | string    | Key of the entry.
| func       | function  | Mapping function that accepts the existing mapped value (or null, if there is no associated mapping). The returned value replaces the existing mapped value for the specified key. If the returned value is null then the value is removed from the map.
| ttlSeconds | number    | Maximum time to live in seconds for this entry to stay in the map. (0 means infinite, negative means map config default or infinite if map config is not available).
|===

[source,js]
----
const gridLib = require('/lib/xp/grid');

const sharedMap = gridLib.getMap('mapId');

let newValue = sharedMap.modify({
  key: 'key',
  func: function (oldValue) {
      return oldValue + 1;
  },
  ttlSeconds: 2 * 60 * 1000
});
----
