= Websocket API
:toc: right
:imagesdir: ../images

Websocket functions.

== Usage

Add the following to your `build.gradle` file:

[source,groovy]
----
dependencies {
  include "com.enonic.xp:lib-websocket:${xpVersion}"
}
----

in your controller, add an import statement:

[source,typescript]
----
import webSocketLib from '/lib/xp/websocket';
----

You are now ready to use the library functionality.

== Functions

=== addToGroup

Add an id to a socket group.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name  | Type   | Description
| group | string | Group name
| id    | string | Socket id
|===

[.lead]
Returns

*void*

[.lead]
Example

[source,typescript]
----
import {addToGroup} from '/lib/xp/websocket';

addToGroup('people', session.id);
----

=== removeFromGroup

Remove an id from a socket group.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name  | Type   | Description
| group | string | Group name
| id    | string | Socket id
|===

[.lead]
Returns

*void*

[.lead]
Example

[source,typescript]
----
import {removeFromGroup} from '/lib/xp/websocket';

removeFromGroup('people', session.id);
----

=== send

Send message directly to a socket id.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| id      | string | Socket id
| message | string | Text message
|===

[.lead]
Returns

*void*

[.lead]
Example

[source,typescript]
----
import {send} from '/lib/xp/websocket';

send(session.id, 'You said - ' + message);
----

=== sendToGroup

Send message to all sockets in group.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| group   | string | Group name
| message | string | Text message
|===

[.lead]
Returns

*void*

[.lead]
Example

[source,typescript]
----
import {sendToGroup} from '/lib/xp/websocket';

sendToGroup('people', 'Notice this message!');
----

=== getGroupSize

image:xp-760.svg[XP 7.6.0,opts=inline] Get number of all sockets in group.

NOTE: Calculating size of a group has a linear cost from total number of sockets.
Consider using this method only if building a message is a resource consuming operation, otherwise it is better to simply `sendToGroup`.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| group   | string | Group name
|===

[.lead]
Returns

*number*

[.lead]
Example

[source,typescript]
----
import {getGroupSize} from '/lib/xp/websocket';

getGroupSize('people');
----
