= Content Project Library
:toc: right
:imagesdir: ../images

NOTE: This library has been introduced in XP 7.3.0.

This library contains functions for management of Content Projects.

== Usage

Add the following dependency to your `build.gradle` file:

[source,groovy]
----
dependencies {
  include "com.enonic.xp:lib-project:${xpVersion}"
}
----

In your JavaScript controller, add a `require` statement:

[source,js]
----
const projectLib = require('/lib/xp/project');
----

== Functions


=== addPermissions

Adds permissions to an existing Content Project.
To modify permissions, user must have `Owner` permissions for the project, or either `system.admin` or `cms.admin` role.

TIP: You can read about project permissions in the dedicated link:https://developer.enonic.com/docs/content-studio/stable/projects#roles[Content Projects] section

[.lead]
Parameters

[%header,cols="1%,44%,55%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| id | string | Unique project id to identify the project.
| permissions | Object.<string, string[]> | Project permissions to add. 1 to 5 properties where key is role id and value is an array of principals.
|===

[.lead]
Returns

*Object* : All current project permissions.

[.lead]
Example

.Add permissions to a project with id 'my-project'
[source,js]
----
var projectLib = require('/lib/xp/project');

var currentPermissions = projectLib.addPermissions({
    id: 'my-project',
    permissions: {
        owner: ['user:mystore:user1', 'user:mystore:user2'],
        editor: ['user:mystore:user3']
    }
});
----

.Sample response
[source,JSON]
----
{
  'id': 'my-project',
  'permissions': {
        'owner': [
            'user:mystore:user1',
            'user:mystore:user2'
        ],
        'editor': [
            'user:mystore:user3'
        ]
    }
}
----


=== create

Creates a new Content Project. Only `system.admin` and `cms.admin` roles have permissions to create new projects.


[.lead]
Parameters

[cols="1,45,1,53a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Attributes | Description
| id | string | | Unique project id (alpha-numeric characters and hyphens allowed).
| displayName | string | | Project display name.
| parent | string | <optional> | image:xp-760.svg[XP 7.6.0,opts=inline] Parent project id. If provided, the new project will be a Content Layer that automatically inherits changes from the parent project.

| description | string | <optional> | Project description.
| language | string | <optional> | Default project language.
| siteConfig | Object.<string, Object>[] | <optional> | Applications (with optional configurations) to be assigned to the project
[stripes=none,cols="1,49,50"]
!===
! Name ! Type ! Description
! applicationKey ! string ! Application key
! config ! Object ! Application config json
!===
| permissions | Object.<string, string[]> | <optional> | Project permissions. 1 to 5 properties where key is role id and value is an array of principals.
[stripes=none,cols="1,49,50"]
!===
! Name ! Type ! Description
! role ! string ! Role id (one of `owner`, `editor`, `author`, `contributor`, `viewer`).
! principals ! string[] ! Array of principals.
!===
| readAccess | Object.<string, boolean> | | Read access settings.
[stripes=none,cols="1,1,98"]
!===
! Name ! Type ! Description
! public ! boolean ! Public read access (READ permissions for `system.everyone`).

!===
|===

[.lead]
Returns

*Object* : Project object.


[.lead]
Example

.Create a Content Project with minimal properties
[source,js]
----
var projectLib = require('/lib/xp/project');

try {
    var project = projectLib.create({
        id: 'my-project',
        displayName: 'My Content Project',
        readAccess: {
            public: true
        }
    });
} catch (e) {
    log.error('Failed to create a project: ' + e);
}
----

.Sample response
[source,JSON]
----
{
  'id': 'my-project',
  'displayName': 'My Content Project',
  'permissions': [],
  'readAccess': {
    'public': true
  }
}
----

.Create a Content Project with extended properties
[source,js]
----
var projectLib = require('/lib/xp/project');

var project = projectLib.create({
    id: 'my-project',
    displayName: 'My Content Project',
    description: 'Some exciting content is stored here',
    language: 'no',
    permissions: {
        owner: ['user:mystore:user1'],
        editor: ['user:mystore:user2'],
        author: ['user:mystore:user3'],
        contributor: ['user:mystore:user4'],
        viewer: ['user:mystore:user5']
    },
    siteConfig: [{
            applicationKey: 'app1',
            config: {
                a: 'b'
            }
        } ,{
            applicationKey: 'app2',
            config: {
                a: true,
                b: 3.4
            }
        }],
    readAccess: {
        public: false
    }
});
----

.Sample response
[source,JSON]
----
{
  'id': 'my-project',
  'displayName': 'My Content Project',
  'description': 'Some exciting content is stored here',
  'language': 'no',
  'siteConfig': [
        {
            'applicationKey': 'app1',
            'config': {
                'a': 'b'
            }
        },
        {
            'applicationKey': 'app2',
            'config': {
                'a': true,
                'b': 3.4
            }
        }
    ],
  'permissions': {
    'owner': [
        'user:mystore:user1'
    ],
    'editor': [
        'user:mystore:user2'
    ],
    'author': [
        'user:mystore:user3'
    ],
    'contributor': [
        'user:mystore:user4'
    ],
    'viewer': [
        'user:mystore:user5'
    ]
  },
  'readAccess': {
    'public': false
  }
}
----

=== delete

Deletes an existing Content Project and the project repository along with all the data inside.
To delete a project, user must have either `system.admin` or `cms.admin` role.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| id | string | Unique project id to identify the project.
|===

[.lead]
Returns

*boolean* : `true` if the project is successfully deleted.


[.lead]
Example

.Delete an existing content project
[source,js]
----
var projectLib = require('/lib/xp/project');

var result = projectLib.delete({
    id: 'my-project'
});
----

.Sample response
[source,JSON]
----
true
----

=== get

Returns an existing Content Project.
To get a project, user must have permissions for this project, or either `system.admin` or `cms.admin` role.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| id | string | Unique project id to identify the project.
|===

[.lead]
Returns

*Object* : Content Project object or `null` if not found.

[.lead]
Example

.Fetch an existing content project
[source,js]
----
var projectLib = require('/lib/xp/project');

var project = projectLib.get({
    id: 'my-project'
});
----

.Sample response
[source,JSON]
----
{
    'id': 'my-project',
    'displayName': 'My Content Project',
    'permissions': {
        'owner': [
            'user:mystore:user1'
        ],
        'editor': [
            'user:mystore:user2'
        ]
    },
    'readAccess': {
        'public': true
    }
}
----

=== list

Returns all Content Projects that user in the current context has permissions for.
Users with `system.admin` or `cms.admin` roles will get the list of all projects.

[.lead]
Returns

*Object[]* : Array of Content Project objects.


[.lead]
Example

.Fetch the list of existing content projects
[source,js]
----
var projectLib = require('/lib/xp/project');

var projects = projectLib.list();
----

.Sample response
[source,JSON]
----
[{
    'id': 'default',
    'displayName': 'Default',
    'description': 'Default project'
},
{
    'id': 'my-project',
    'displayName': 'My Content Project',
    'permissions': [],
    'readAccess': {
        'public': true
    }
}]
----

=== modify

Modifies an existing Content Project.
To modify a project, user must have `Owner` permissions for this project, or either `system.admin` or `cms.admin` role.

[.lead]
Parameters

[%header,cols="1,1,1,97a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Attributes | Description
| id | string | | Unique project id (alpha-numeric characters and hyphens allowed).
| displayName | string | <optional> | Project display name.
| description | string | <optional> | Project description.
| language | string | <optional> | Default project language.
| siteConfig | Object.<string, Object>[] | <optional> | Applications (with optional configurations) to be assigned to the project.
[stripes=none,cols="1,49,50"]
!===
! Name ! Type ! Description
! applicationKey ! string ! Application key
! config ! Object ! Application config json
!===
|===

[.lead]
Returns

*Object* : Modified project object.


[.lead]
Example

.Modify an existing content project
[source,js]
----
var projectLib = require('/lib/xp/project');

var project = projectLib.modify({
    id: 'my-project',
    displayName: 'New project name',
    description: 'New project description',
    language: 'en',
    siteConfig: [{
            applicationKey: 'app1',
            config: {
                a: 'b'
            }
        } ,{
            applicationKey: 'app2',
            config: {
                a: true,
                b: 3.4
            }
        }],
});
----

.Sample response
[source,JSON]
----
{
    'id': 'my-project',
    'displayName': 'New project name',
    'description': 'New project description',
    'language': 'en',
    'siteConfig': [
        {
            'applicationKey': 'app1',
            'config': {
                'a': 'b'
            }
        },
        {
            'applicationKey': 'app2',
            'config': {
                'a': true,
                'b': 3.4
            }
        }
    ],
    'permissions': {},
    'readAccess': {
        'public': true
    }
}
----

=== modifyReadAccess

Toggles public/private READ access for an existing Content Project. This will modify permissions on ALL the content items inside the project
repository by adding or removing READ access for `system.everyone`.
To modify READ access, user must have `Owner` permissions for the project, or either `system.admin` or `cms.admin` role.

[.lead]
Parameters

[%header,cols="1,35,64a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Description
| id | string | Unique project id (alpha-numeric characters and hyphens allowed).
| readAccess | Object.<string, boolean> | Read access settings.
[stripes=none,cols="1,1,98"]
!===
! Name ! Type ! Description
! public ! boolean ! Public read access (READ permissions for `system.everyone`).

!===
|===

[.lead]
Returns

*Object* : Current state of public READ access.


[.lead]
Example

.Set content project as not available for public READ access
[source,js]
----
var projectLib = require('/lib/xp/project');

var currentPermissions = projectLib.addPermissions({
    id: 'my-project',
    readAccess: {
        public: false
    }
});
----

.Sample response
[source,JSON]
----
{
    'id': 'my-project',
    'readAccess': {
        'public': false
    }
}
----

=== removePermissions

Removes permissions from an existing Content Project.
To remove permissions, user must have `Owner` permissions for the project, or either `system.admin` or `cms.admin` role.

[.lead]
Parameters

[%header,cols="1,40,59a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Description
| id | string | Unique project id (alpha-numeric characters and hyphens allowed).
| permissions | Object.<string, string[]> | Project permissions to delete. 1 to 5 properties where key is role id and value is an array of principals.
[stripes=none,cols="1,49,50"]
!===
! Name ! Type ! Description
! role ! string ! Role id (one of `owner`, `editor`, `author`, `contributor`, `viewer`).
! principals ! string[] ! Array of principals to delete from this project role.
!===

|===

[.lead]
Returns

*Object* : All current project permissions.

.Adds and then removes permissions from an existing content project
[source,js]
----
var projectLib = require('/lib/xp/project');

projectLib.addPermissions({
    id: 'my-project',
    permissions: {
        owner: ['user:mystore:user1', 'user:mystore:user2'],
        editor: ['user:mystore:user3']
    }
});

var currentPermissions = projectLib.removePermissions({
    id: 'my-project',
    permissions: {
        owner: ['user:mystore:user2']
    }
});
----

.Sample response
[source,JSON]
----
{
    'id': 'my-project',
    'permissions': {
        'owner': [
            'user:mystore:user1'
        ],
        'editor': [
            'user:mystore:user3'
        ]
    }
}
----

=== getAvailableApplications
image:xp-7110.svg[XP 7.11.0,opts=inline]


Returns available applications of a specified project. The result contains active apps assigned to the project and all of its parents, if any.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| id | string | Unique project id to identify the project.
|===

[.lead]
Returns

*string[]* : Application keys.

[.lead]
Example

.Fetch available applications.
[source,js]
----
var projectLib = require('/lib/xp/project');

var project = projectLib.getAvailableApplications({
    id: 'my-project'
});
----

.Sample response
[source,JSON]
----
['app1', 'app2']
----
