= Authentication Library
:toc: right
:imagesdir: images

This library contains built-in authentication functions.

== Usage

Add the following into your `build.gradle` file:

[source,groovy]
----
dependencies {
  include 'com.enonic.xp:lib-auth:${xpVersion}
}
----

In your JavaScript controller, add a require statement:

[source,js]
----
const authLib = require('/lib/xp/auth');
----

You are now free to use the library functionality.


== Functions

=== addMembers

Adds members to a principal (user or role).

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| principalKey | string | Key of the principal to add members to
| members | Array.<string> | A list of the new memebers that should be added to the principal
|===

[.lead]
Returns

*void*


=== changePassword

Changes password for specified user.

[.lead]
Parameters

A JSON object with the following keys and their value:

[%header,cols="1%,99%a"]
[frame="none"]
[grid="none"]
|===
| Name | Description
| userKey | The key of the user to change password for
| password | The new password
|===

[.lead]
Returns

*void*

=== createGroup

Creates a group.

[.lead]
Parameters

A JSON object with the following keys and their value:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Description
| idProvider | string | Key for id provider where the group will be created
| name | string | Group name
| displayName | string | Group display name
| description | string | A description of the principal
|===

[.lead]
Returns

*object* : The created group.

[.lead]
Example

.Creating a group named "group-a"
[source,js]
----
var group = authLib.createGroup({
    idProvider: 'myIdProvider',
    name: 'group-a',
    displayName: 'Group A',
    description: "description"
});
----

.Sample response
[source,js]
----
{
    "type": "group",
    "key": "group:system:group-a",
    "displayName": "Group A",
    "modifiedTime": "1970-01-01T00:00:00Z",
    "description": "description"
}
----

=== createRole

Creates a role.

[.lead]
Parameters

A JSON object with the following keys and their value:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Description
| name | string | Role name
| displayName | string | Role display name
| description | string | A description of the role
|===

[.lead]
Returns

*object* : The created group.

[.lead]
Example

.Creating a role named "aRole"
[source,js]
----
var role = authLib.createRole({
    name: 'aRole',
    displayName: 'Role Display Name',
    description: 'description'
});
----

.Sample response
[source,js]
----
{
    'type': 'role',
    'key': 'role:aRole',
    'displayName': 'Role Display Name',
    'modifiedTime': '1970-01-01T00:00:00Z',
    'description': 'description'
}
----

=== createUser

Creates a user.

[.lead]
Parameters

A JSON object with the following keys and their value:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Description
| idProvider | string | Key for id provider where the user will be created
| name | string | User login name
| displayName | string | User display name
| email | string | Optional user e-mail
|===

[.lead]
Returns

*object* : The created group.

[.lead]
Example

.Creating a user named "userName"
[source,js]
----
var user = authLib.createUser({
    idProvider: 'myIdProvider',
    name: 'user1',
    displayName: 'The One And Only',
    email: 'user1@enonic.com'
});
----

.Sample response
[source,js]
----
{
    "type": "user",
    "key": "user:enonic:user1",
    "displayName": "The One And Only",
    "modifiedTime": "1970-01-01T00:00:00Z",
    "disabled": false,
    "email": "user1@enonic.com",
    "login": "user1",
    "idProvider": "myIdProvider"
}
----

=== deletePrincipal

Deletes the principal with the specified key.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| principalKey | string | Key of the principal to delete
|===

[.lead]
Returns

*boolean* : `true` if the principal was deleted, `false` otherwise

[.lead]
Example

.Deleting a user
[source,js]
----
var deleted = authLib.deletePrincipal('user:myIdProvider:userId');
----

=== findPrincipals

Search for principals matching the specified criteria.

A JSON object with the following keys and their value.  All parameters are optional:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Description
| type | string | Principal type to look for, one of: 'user', 'group' or 'role'. If not specified all principal types will be included.
| idProvider | string | Key of the id provider to look for. If not specified all id providers will be included.
| start | string | First principal to return from the search results. It can be used for pagination.
| count | string | A limit on the number of principals to be returned
| name | string | Name of the principal to look for
| searchText | string | Text to look for in any principal field.
|===

[.lead]
Returns

*object* : The "total" number of principals matching the search, the "count" of principals included, and an array of "hits" containing the principals.

[.lead]
Example

.Searching for principals for 'user1'
[source,js]
----
var result = authLib.findPrincipals({
    idProvider: 'user-store',
    start: 0,
    count: 10,
    searchText: 'user1'
});
----

.Sample response
[source,js]
----
{
    "type": "user",
    "key": "user:enonic:user1",
    "displayName": "The One And Only",
    "modifiedTime": "1970-01-01T00:00:00Z",
    "disabled": false,
    "email": "user1@enonic.com",
    "login": "user1",
    "idProvider": "myIdProvider"
}
----


=== findUsers

Search for users matching the specified query.

A JSON object with the following keys and their value:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Description
| query | string | Query expression
| start | number | Optional start index for paging
| count | number | Optional number of users to fetch at a time
| sort | string | Optional sorting expression
| includeProfile | boolean | If set to `true`, a full profile of each user will be included in the result
|===

[.lead]
Returns

*object* : An object containg the total number of hits, the number returned and an array of the hits.

[.lead]
Example

.Searching for the first person in the `Juve` family.
[source,js]
----
var findUsersResult = auth.findUsers({
    count: 1,
    query: "displayName LIKE '*Juve'"
});
----

.Sample response
[source,js]
----
{
    "total": 2,
    "count": 1,
    "hits": [
        {
            "type": "user",
            "key": "user:system:jorgen-juve",
            "displayName": "Jørgen Juve",
            "disabled": false,
            "email": "jju@enonic.com",
            "login": "jorgen-juve",
            "idProvider": "system"
        }
    ]
}
----


=== generatePassword

Generates a random secure password that may be suggested to a user.

[.lead]
Parameters

None

[.lead]
Returns

*string* : A suggestion for a secure password

=== getIdProviderConfig

This function returns the ID provider configuration. It is meant to be called from an ID provider controller.

[.lead]
Parameters

None

[.lead]
Returns

*object* : A JSON object with all the values in the configuration

=== getMembers

Returns a list of principals that are members of the specified principal.

=== getMemberships

Returns the list of principals which the specified principal is a member of.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| principalKey | string | Principal key to retrieve memberships for
| transitive | boolean | Retrieve transitive memberships.  Considered `false` if not specified
|===

[.lead]
Returns

*Array.<string>* : A list of the principals that the specified principal is a member of

[.lead]
Example

.Searching for direct memberships of 'user1'
[source,js]
----
var result = authLib.getMemberships('user:enonic:user1');
----

.Sample response
[source,js]
----
[
    "role:system.admin.login",
    "group:system:content-managers"
]
----

.Searching for transitive memberships of 'user1'
[source,js]
----
var result = authLib.getMemberships('user:enonic:user1', true);
----

.Sample response
[source,js]
----
[
    "role:system.admin.login",
    "group:system:content-managers",
    "role:cms.expert",
    "role:cms.cm.app"
]
----

=== getPrincipal

Returns the principal with the specified key.

=== getProfile

Returns the profile of a user.

=== getUser

Returns the logged-in user. If not logged-in, this will return _undefined_.

=== hasRole

Checks if the logged-in user has the specified role.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| role | string | The role to check for
|===

[.lead]
Returns

*boolean* : `true` if the current user has the role, `false` otherwise

[.lead]
Example

.Checking a role
[source,js]
----
var hasRole = auth.hasRole('system.admin');
----

=== login

Login a user through the specified idProvider, with userName and password.

[.lead]
Parameters

A JSON object with the following keys and their value:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| user | string | Mandatory name of the user to log in
| password | string | Password for the user. Ignored if skipAuth is set to true, mandatory otherwise.
| idProvider | string | Name of id provider where the user is stored. If not specified it will try all available id providers, in alphabetical order.
| skipAuth | boolean | Skip authentication.  Default is `false` if not specified.
| sessionTimeout | number | Session timeout (in seconds). By default, the value of session.timeout from `com.enonic.xp.web.jetty.cfg`
|===

[.lead]
Returns

*object* : The logged in user

[.lead]
Example

.Logging in a user
[source,js]
----
    var loginResult = auth.login({
        user: 'user1',
        password: 'myPwd1',
        idProvider: 'myIdProvider'
    });
----

.Sample response
[source,js]
----
{
    "authenticated":true,
    "user":{
        "type":"user",
        "key":"user:system:jsi",
        "displayName":"The One And Only",
        "disabled":false,
        "email":"user1@enonic.com",
        "login":"user1",
        "idProvider":"myIdProvider"
    }
}
----


=== logout

Logout the currently logged-in user.

[.lead]
Parameters

None

[.lead]
Returns

*void*

=== modifyGroup

Retrieves the group specified and updates it with the changes applied.

=== modifyProfile

This function retrieves the profile of a user and updates it.

=== modifyRole

Retrieves the role specified and updates it with the changes applied.

=== modifyUser

Retrieves the user specified and updates it with the changes applied.

=== removeMembers

Removes members from a principal (user or role).
