= IO API
:toc: right
:imagesdir: images

IO related functions.

== Usage

Add the following to your `build.gradle` file:

[source,groovy]
----
dependencies {
  include "com.enonic.xp:lib-io:${xpVersion}"
}
----

in your controller, add an import statement:

```typescript
import ioLib from '/lib/xp/io';
```

You are now ready to use the library functionality.

== Functions

=== getMimeType

Returns the mime-type from a name or extension.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name  | Type   | Description
| name | string | Name of file or extension
|===

[.lead]
Returns

*string* : mime-type from a name or extension.

[.lead]
Example

```typescript
import {getMimeType} from '/lib/xp/io';

// Returns mime-type for a file name.
const type = getMimeType('myfile.txt');
log.info('Mime type is %s', type);
```

=== getResource

Looks up a resource.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name  | Type   | Description
| key | string | Resource key to look up
|===

[.lead]
Returns

*Resource* : Resource reference.

[.lead]
Examples

```typescript
import {getResource} from '/lib/xp/io';

// Returns a file by name.
const res1 = getResource('/lib/xp/examples/io/sample.txt');
const exists = res1.exists();
const size = res1.getSize();
const stream = res1.getStream();
```

```typescript
import {getResource} from '/lib/xp/io';

// Returns a file by reference.
const res2 = getResource(resolve('./sample.txt'));
if (res2.exists()) {
    log.info('Resource exists');
}
```

=== getSize

Returns the size of a stream.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| stream      |  | Stream to get size of
|===

[.lead]
Returns

*number* : Returns the size of a stream.

[.lead]
Example

```typescript
import {getSize} from '/lib/xp/io';

// Returns the size of a stream.
const size = getSize(stream);
log.info('Stream size is %s bytes', size);
```

=== newStream

Returns a new stream from a string.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| text   | string | String to create a stream of
|===

[.lead]
Returns

_*_ : A new stream.

[.lead]
Example

```typescript
import {newStream} from '/lib/xp/io';

// Creates a new stream from a string.
const stream = newStream('Hello World');
```

=== processLines

Process lines from a stream.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| stream   |  | Stream to read lines from
| func   | function | Callback function to be called for each line
|===

[.lead]
Example

```typescript
import {processLines} from '/lib/xp/io';

let num = 0;

// Process lines from stream.
processLines(stream, function (line) {
    num++;
    log.info('Line %s: %s', num, line);
});
```

=== readLines

Read lines from a stream.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| stream   |  | Stream to read lines from
|===

[.lead]
Returns

*string[]* : Lines as an array.

[.lead]
Example

```typescript
import {readLines} from '/lib/xp/io';

// Reads lines from stream.
const lines = readLines(stream);
log.info('Num lines: %s', lines.length);
```

=== readText

Read text from a stream.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name    | Type   | Description
| stream   |  | Stream to read text from
|===

[.lead]
Returns

*string* : The text read from stream or string.

[.lead]
Example

```typescript
import {readText} from '/lib/xp/io';

// Reads text from stream.
const text = readText(stream);
log.info('Text: %s', text);
```
