= Event API
:toc: right
:imagesdir: images

This library contains functions to create and listen to instance local or cluster distributed events.

== Usage

Add the following to your `build.gradle` file:

[source,groovy]
----
dependencies {
  include "com.enonic.xp:lib-event:${xpVersion}"
}
----

in your controller, add an import statement:

[source,typescript]
----
import eventLib from '/lib/xp/event';
----

You are now ready to use the library functionality.

[NOTE]
====
Several standard XP APIs already produce and publish events.
For more details, check out the <<lib-node#events, node API>>, <<lib-repo#events, repository API>>, and <<lib-task#events, task API>>
====

== Functions

=== listener

Adds an event listener to the system

[.lead]
Parameters

An object with the following keys and their values:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| type | string | Event type pattern
| callback | function | Callback event listener
| localOnly | boolean | Local events only (default to false)
|===

[.lead]
Returns

`null`

[.lead]
Example

.Adding a listener that logs the event
[source,typescript]
----
eventLib.listener({
    type: 'node.*',
    localOnly: false,
    callback: (event) => {
        log.info('event: %s', JSON.stringify(event));
    }
});
----

=== send

Sends a custom event.  All custom events are prefixed with "custom.".

[.lead]
Parameters

An object with the following keys and their values:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Kind | Details
| type | string | Event type
| distributed | boolean | `True` if it should be distributed in cluster
| data| object | Additional data for event.
|===

[.lead]
Returns

`null`

[.lead]
Example

.Send a custom event into the system
[source,typescript]
----
eventLib.send({
    type: 'myEvent',
    distributed: false,
    data: {
        a: 1,
        b: 2
    }
});
----
