= API and core libraries
include::.variables.adoc[]
:toc: right
:imagesdir: images


Enonic XP provides multiple interfaces, from web endpoints, via Javascript libraries to the core Java API.
This section offers detailed documentation on all our APIs.

TIP: Looking for our *Headless CMS GraphQL API?* It is available as an https://developer.enonic.com/docs/guillotine/stable[application library]. To give it a quick spin, launch a cloud trial or check out the https://developer.enonic.com/guides/headless-cms-intro[headless CMS introduction guide]



== Endpoints

There are two endpoints for calling REST-methods, the Management endpoint and the Statistics endpoint.
These provide many options for querying the server and executing commands to manage the data.

== JavaScript libraries

Enonic XP comes with a large number of build in JavaScript libraries for developing websites.
Some are straight helper classes, other provide interaction with the data in the site.
Please check out all of them in the submenu.

== JavaDoc

Java developers, or anyone interested in the platform core may browse https://repo.enonic.com/public/com/enonic/xp/docs/{version}/docs-{version}-javadoc.zip!/index.html[the XP JavaDoc]
or https://repo.enonic.com/public/com/enonic/xp/docs/{version}/docs-{version}-javadoc.zip[download it as a zip file].
