= Purple.js Server-Side Framework
:toc: right
:imagesdir: framework/images

More than a Headless CMS - Enonic is a back-end for your digital experiences.

== Introduction

Enonic offers a powerful Server-side JavaScript/TypeScript development framework. The framework, developers may <<todo#, build custom APIs>>, <<todo#, extend the platform>> or even <<build web-sites>>. Developers get full access to the Enonic platform, including persistence, background jobs, caching and much more. 

== Enonic apps

== Runtime

Here are some highlights:

* *Integrated* with the Enonic applications runtime. Ship and execute server-side TypeScript/JavaScript.
* *Compatible* across all releases of XP within a major version i.e. 7.x.x
* *Supports* HTTP request-response, clustered events and and background task execution
* *Multithreaded* for ease of development and effective use of multi-core CPU arcitectures
* *Fast and performant* as JavaScripts are compiled and adapted to the underlying architecture.
* *Based on the https://wiki.commonjs.org/wiki/Modules/1.1[CommonJS module specification]*
* *Powered by the GraalVM* Unlike most JavaScript frameworks, this is not powered by Node.js, but uses the Nashorn scripting engine. Next major release of XP is expected to be using GraalJS.
