= Enonic Framework
:toc: right
:imagesdir: framework/images

Enonic applications are built using Enonic's server-side JavaScript controller framework. Applications are executed by the <<runtime#, XP runtime>>, which means it can take advantage of it's modular architecture and get access to all platform <<api#, APIs>> as well as access management and IDprovider features. 

Here are some highlights:

* *Integrated* with the Enonic applications runtime. Ship and execute server-side TypeScript/JavaScript.
* *Compatible* across all releases of XP within a major version i.e. 7.x.x
* *Supports* HTTP request-response, clustered events and and background task execution
* *Multithreaded* for ease of development and effective use of multi-core CPU arcitectures
* *Fast and performant* as JavaScripts are compiled and adapted to the underlying architecture.
* *Based on the https://wiki.commonjs.org/wiki/Modules/1.1[CommonJS module specification]*
* *Powered by the GraalVM* Unlike most JavaScript frameworks, this is not powered by Node.js, but uses the Nashorn scripting engine. Next major release of XP is expected to be using GraalJS.
