= The XP manifesto
:toc: right
:imagesdir: images

The purpose of Enonic XP is to:

* simplify development and maintenance of complex web apps and sites
* combine freedom from proprietary cloud services with the ability to deploy anywhere
* bring a smile on your face

To achieve these goals, we have focused on the following:

== Performance

Enonic XP is seriously fast, and scalable.

* Installing XP, building and deploying your first application takes less than 5 minutes.
* Enonic XP has a lightning fast embedded storage, built on top of Elasticsearch.
* XP is easy to learn, as new developers are typically trained and productive in less than a day
* Enonic offers application starter kits, so you get a flying start every time

== Architecture

The Enonic XP runtime, and the platform services can be seen as a framework for your app.
This means that application built on Enonic XP are essentially micro services.

You can use XP for a single application, run multiple dedicated apps in a cluster,
and even run multiple apps within a single runtime - for better resource utilization or modularization.

== Simplicity

Enonic XP offers a unique and tightly integrated application stack.
The runtime, storage/search, IAM (Identity and Access Management) and CMS are all released and versioned together.

This simplifies everything from the SDK, to building, testing and deploying applications, not to mention scaling.

You may also integrate XP and your apps with other platforms or infrastructure services as needed.

== Javascript

The <<runtime/framework.adoc#,XP Javascript framework>> is based on the CommonJS specification.
But unlike most server Javascript platforms, Enonic XP runs on the JVM.

This brings benefits like:

* Multithreading (with ability to utilize multi-core processing)
* Access to and ability to execute Java in addition to Javascript
* Performance gains from the highly optimized JVM

If needed, XP can easily be configured to execute and interact with NodeJS containers,
especially in containerized environments.

== Embedded CMS

CMS can be a headache. Unlike any other application stack, Enonic XP includes an embedded powerful CMS and API.
It is fully optional to use for your projects.
Wether you are looking for a traditional, headless or hybrid CMS, XP got you covered.

The CMS builds directly on the other platform components. It enables you to create multiple sites in one instance,
and add multiple applications to a single site.

The editorial interface can be installed as an app, and we are confident it will bring a smile on your editors face as well.

== Freedom

Last, but not least, Enonic XP is fully open sourced, licensed under GPL 3 with a linking exception.
This means that applications and tools built on XP are not affected by GPL, and can be licensed however you like.

NOTE: *Apache license* Almost all apps, libraries and other utilities on https://market.enonic.com[Enonic Market] are licensed with the permissive Apache license.

As open source software, Enonic XP also leaves you free to run the software wherever you like, on premises or in the cloud.

Should you be using XP for a mission critical deployment,
it is nice to know that Enonic offers professional cloud services and software support.

More information on https://enonic.com
