= Release Notes
include::variables.adoc[]
:toc: right
:imagesdir: release

NOTE: *Breaking change* XP 7 contains breaking changes. Follow the <<upgrade#,upgrade instructions>> carefully to secure a successful upgrade.

== Introduction
Enonic XP 7 takes a major leap in simplifying application development and making the platform leaner and more flexible.

The biggest highlights of XP 7 is not the core platform, but all the changes around it:

* New documentation - The documentation you are reading was created from scratch for XP 7
* <<Developer portal>> - All XP related developer resources and docs in one place
* <<Enonic CLI>> - For managing XP development project, also replaces the toolbox shell script
* <<Native distributions>>. The Java Virtual Machine is now bundled with XP
* <<Content Studio as an app>> - available for download from Enonic Market.

== Developer portal

In order for developers to better and more easily navigate the XP ecosystem, we created a dedicated portal.
The portal contains

XP docs: The XP core platform documentation (which you are reading now)
Reference docs:: For all XP related apps, starters, libraries and more that are built by Enonic.
Hands on guides:: Practical how-to guides an tutorials, including the getting started page

The portal is naturally built as an XP app itself.
The geeky fact is that all docs and most guides are written in Asciidoctor together with the actual product.
When commit, changes to the docs are automatically checked out compiled and imported to the portal.
This optimizes how developers produce content,
while taking advantage of everything XP brings offers at the same time.

We plan to release the core elements of the doc portal on the market in the future.


== Enonic CLI

The brand new Enonic Command Line Interface - "Enonic CLI" is released at the same time as XP 7, but is versioned independently.
The CLI not only replaces the old toolbox script, but introduces new and flexible ways of installing XP and managing development environments.

Installing CLI, Enonic XP, building and deploying your first app can now be done with three simple commands as described in the getting started section of the developer portal https://developer.enonic.com/start

The CLI is available for Mac, Linux and Windows


== Native distributions

The biggest conceptual change to XP is that Java (the JVM) is no longer required in order to run XP.
XP 7 ships with Java 11 embedded. As such, we now release native distributions of XP for the three major platforms, Mac, Windows and Linux.
Expect future versions of XP to make more use of native capabilities and non-Java based functionality.
As always, you will never have to worry about portability when writing XP apps.

There are several reasons for this move:

* Developers no longer need to install or juggle with different versions of the JVM
* Installation of XP is faster and sleeker than ever
* We can take advantage of native/non Java functionality when required

With this change, XP is now available in SDK and Server version.
The SDK includes the full Java Development Kit,
where the server edition uses a slimmed down versjon of the JVM, and can be further optimized for production use.


== Content Studio as an app

Content Studio, the CMS editorial interface has been moved out of the XP core.
It is now available as a separate application on https://market.enonic.com/vendors/enonic/content-studio[Enonic Market]

Content Studio can now be released more frequently than the XP core.
But expect new versions of Content Studio to be released along with new features in the XP core.

For Content Studio release notes, check out the https://developer.enonic.com/docs/content-studio[new documentation].


== CMS core

Even if Content Studio can be installed as a separate application,
The XP core still ships with the <<api/lib-content#,content API>> and <<reference/runtime/site engine#, site engine>> that applications depend on.

=== Image styles

XP 7 introduces a new feature in the rich text editor called "Image styles".
Image styles consist of both client side styling (css), and image service rendering specifications.

The rich text editor was previously limited to pre-defined and hard-coded styles, such as "cinema (21:9) or square(1:1)".
Now, application developers may define custom styles that control both server side rendering aspect ratio, and specify classes to annotate the specific image.

TODO IMAGE

=== Projects are coming

Customers with many sites have requested better support for isolation of sites, and who can access specific them.
Our solution to this is creating sites in different "projects", each project will be using its own repo.
XP 7 (and Content Studio) does not yet fully implement this features, but prepares the foundation for supporting it.

You will notice this through the following change:

* The default CMS repo is renamed from "cms-repo" to "com.enonic.cms.default".
* New projects will be using the extension as project name, i.e. project "myproject" will use repo "com.enonic.cms.myproject"
* The site engine URLs now contain project name - i.e. /site/<project>/<branch>/<content-path>


=== Rich text references

References to images or other content in the rich text editor are now stored explicitly in the underlying node API.
The publishing wizard will now identify and include these dependencies like all other references - no more missed items during publishing.


=== Stemmed content

Content flagged with a language is now automatically stemmed during indexing (trimming words to their root form for better hits).
This is done using the standard Elasticsearch stemmer.
This is achieved by adding a stemmed version of the  _allText property, combined with a new query function.

=== Better page indexing

Pages, and their components are now indexed differently.
Rather than just looking for text within a page, developers may now search for any configuration property,
or metadata within a page.

As an example, one may now search the use of a specific part within a site.

TODO: more?

== XP Storage

The XP storage has been refactored for improved performance and disk usage

=== Blobstore improvements

XP persists all data in so-called blobstore segments, one segment for each type of data to persist.
XP 7 introduces new segments for indexconfig and permissions, enabling re-use of these across nodes, and node versions.

On average, this reduces use of disk space between 40 to 80 percent (TODO, verify)

Additionally, each repository now has it's own root entry in the blobstore.
This makes it possible to directly manage blobs associated with a single repository.

=== Version commits

XP automatically creates new versions for each modification of a node.
Where XP 6 would persist all versions forever, XP 7 by default treats all versions as transient.
This means that all versions that are not currently in a branch, may be "garbage collected" at any time in the future.

To prevent versions from being removed, one may also make a "commit".

For the Content API specifically, publishing an item will automatically create a "commit", effectively placing a stamp on the specific versions being published.
Commits have id, committer, and optionally a commit message as meta data.

NOTE: XP 7 does not yet implement the "garbage collector" that removes "uncommitted versions", this will be part of an upcoming release.

== TODO?
