= XP Runtime
:toc: right
:imagesdir: runtime/media

Applications built on the <<framework#,XP framework>> are powered by the XP runtime.
The XP runtime essentially provides the following capabilities:

== HTTP engine

The HTTP engine is responsible for handling any web-based request to the runtime.
By default, the XP runtime serves HTTP requests from port 8080 (customizable).

=== Request pipeline

All HTTP requests are processed through a common pipeline as specified below:

image::http-pipeline.svg[Common HTTP request pipeline, 768px]

Vhost filters:: Request routing based on <<deployment/vhosts#,virtual hosts>>

Java request filters:: Optional Java request filters

Asset service:: Serves <<runtime/asset-service#,static assets>> for the /_/asset/* request patterns

HTTP Services:: Executes <<runtime/http-services#,HTTP services>> for the /_/service/* request patterns

Engine pipeline:: Engine specific processing based on request pattern:
+
====
There are three specialized implementations of the HTTP engine available.

* <<runtime/webapp-engine#,Web app engine>> :8080/webapp/<name-of-webapp>/*
* <<runtime/site-engine#,Site engine>> :8080/site/<repo>/<branch>/*
* <<runtime/admin-engine#,Admin engine>> :8080/admin/*
====

Auth filter::  If the pipeline returns a "401: Unauthorized" error code, the default <<deployment/vhosts#,virtual host defined ID provider>> will be invoked, and may handle the request

Error handler:: If the pipeline returns an error (everything but "200: Ok") that was not handled by an ID provider, an available error handler will kick in.

Java response filters:: Optional Java response filters

Standard error handler:: Finally, if the request fails with an error that is still unhandled, the standard error handler will kick in



== Task Engine

The <<runtime/task-engine#,task engine>> enables developers to run Javascripts as threaded background tasks.
