= XP Runtime
:toc: right
:imagesdir: runtime/images

Applications built on the <<framework#,XP framework>> are powered by the XP runtime.
The XP runtime essentially provides the following capabilities:

== HTTP engine

The HTTP engine is responsible for handling any web-based request to the runtime.
By default, the XP runtime serves HTTP requests from port 8080 (customizable).

Vhost filter:: Request routing based on <<deployment/vhosts#,virtual hosts>>

Java filters:: Optional Java request filters

Asset handler:: Serves <<runtime/assets#,static assets>> for /_/asset/* request patterns

Service handler:: Executes <<runtime/http-services#,HTTP services>> for /_/service/* request patterns

Engine pipeline:: Engine specific processing based on request pattern:

====
There are three specialized implementations of the HTTP engine available.

* <<webapp-engine#,Web app engine>> :8080/webapp/<name-of-webapp>/*
* <<site-engine#,Site engine>> :8080/site/<repo>/<branch>/*
* <<admin-engine#,Admin engine>> :8080/admin/*

All engines share a common request processing pipeline that runs before the specialized handling begins.
====

ID provider::  If the pipeline returns a "401: Unauthorized" error code, the default virtual host defined ID provider will be invoked, and may handle the request

Error handler:: If the pipeline returns an error (everything but "200: Ok") that was not handled by an ID provider, an available error handler will kick in.

Custom Java Filters:: Optional Java response filters

Default error handler:: Finally, if the request fails with an error that is still unhandled, the default error handler will kick in



== Task Engine

The <<tasks#,task engine>> enables developers to run Javascripts as threaded background tasks.
