= Enonic XP Application development
:toc: right
:imagesdir: images

We like to refer to Enonic XP as a "Cloud OS".
Like every other operating system, Enonic XP supports development and deployment of applications.

An XP application can be seen as a microservice based on the Enonic XP runtime. Applications are deployed and run as isolated pieces of code.
However, XP apps also get access to the platform services - such as the NoSQL repo and ID providers.
Together they make out the essential tools needed for delivering powerful back-end applications.

XP apps are not limited to being "Web Applications”. Apps can run background tasks, extend the Admin Console, power websites, offer http services, and even expose internal API’s to other applications.

NOTE: If you are new to Enonic XP, we recommend visiting the https://developer.enonic.com/start[Getting Started documentation]

== CLI

As of Enonic XP 7.0, a powerful CLI is available. The CLI automates installation of Enonic XP, development environments, projects and common tasks.

Read more about CLI: TODO (External documentation?)

== Projects

By projects we commonly mean code organized to build applications or libraries.
The code is typically hosted in a Git repo, and needs to follow a set of principles to work with Enonic XP.

Learn more about <<projects#,XP projects>>

== Javascript framework
Applications are primarily built using a serverside Javascript Framework based on the CommonJS specification.

Get all the details of the <<javascript#,Javascript Framework>>

== Java
Developers can also make use of Java in their projects.

TODO: LINK?

== Build scripts
Enonic XP provides a configurable build system based on Gradle.
The build system is used for a wide range of purposes such as:

* Compiling code
* Running tests
* Creating artifacts (executable files)
* Deploying

Learn more about the <<build-system#,Enonic XP build system>>

== Assets

A common requirement for web apps and sites are serving assets such as javascript files, css and static images.
Enonic XP provides an out-of-the-box solution to this problem.

Learn more about <<assets#,serving Assets>>

== Services

Exposing endpoints and API's for web applications without dealing with hardcoded url mappings or occupying human readable paths is a common problem.
Enonic XP offers a standardized approach to providing an accessing endpoints that solve this issue.

Learn more about the services feature in Enonic XP: TODO LINK

== Libraries

To speed up development and enable a high degree of re-use,
applications can make use of Libraries in addition to your own custom code.

Read more about using libraries in Enonic XP: TODO LINK

TODO: CLEAN AWAY: Libraries can be built almost like you create applications.
Libraries (and applications) are shared through so-called Maven repositories.
An example is https://repo.enonic.com.
Anyone may configure and run their own repository - for internal as well as external use.

== Binary executable TODO REMOVE?

An application is shipped as a JAR (.jar). This is short for Java Archive.
Since Enonic XP is built on top of Java and the powerful OSGi framework, developers with special requirements may utilize capabilities such as exposing and consuming services from other applications.
Enonic XP is also designed to run Serverside JavaScript, and most application projects will not be using any Java at all.


== Application Life Cycle

Applications have the following life-cycle:

* Installed
* Started
* Stopped
* Uninstalled

TODO


== Deployment

Enonic applications can be deployed in many ways - from installation through the UI, via command line deployment to dedicated instances


== Web apps
<<webapps#,Web applications>>

== Sites
<<../cms/index#,Web applications>>


TODO info about deploying XP apps.
